{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.AIModelProvider exposing (Provider)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Provider

-}

import Proto.Rellm.Internals_


{-|  Identifies which external AI service this provider connects to, and carries that service's credentials. Only
 one variant may be set at a time. The `gemini_credentials`/`openai_credentials`/`digitalocean_credentials`
 variants are accepted by
 [`CreateAIModelProvider`](#grpc-api-CreateAIModelProvider)/[`UpdateAIModelProvider`](#grpc-api-UpdateAIModelProvider) --
 see each credentials message below for why the actual key/secret is never sent back in a response.


## Options

### GeminiCredentials

 A [Google Gemini API](https://ai.google.dev/gemini-api) connection, used for image generation/editing (e.g.
 generating Event posters) via its [Interactions API](https://ai.google.dev/gemini-api/docs/image-generation).


### OpenaiCredentials

 An [OpenAI API](https://platform.openai.com/docs/api-reference) connection, used for image
 generation/editing via its [Images API](https://platform.openai.com/docs/guides/image-generation) (GPT Image models).


### AnthropicCredentials

 An [Anthropic API](https://docs.anthropic.com) connection. *Not yet creatable* - Anthropic doesn't offer an image generation API.


### DigitaloceanCredentials

 A [DigitalOcean Gradient AI Platform](https://docs.digitalocean.com/products/gradient-ai-platform/) /
 Serverless Inference connection, used for image generation (no editing - DigitalOcean's
 [Serverless Inference API](https://docs.digitalocean.com/products/gradient-ai-platform/reference/api/serverless-inference/)
 has no `/v1/images/edits`-equivalent endpoint) via its OpenAI-Images-API-shaped
 `/v1/images/generations` endpoint (GPT Image and Stable Diffusion models, re-hosted under DigitalOcean's own
 billing).


-}
type alias Provider =
    Proto.Rellm.Internals_.Proto__Rellm__AIModelProvider__Provider__Provider
