{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.ClusterResource exposing (ClusterResource(..), decodeClusterResource, defaultClusterResource, encodeClusterResource, fieldNumbersClusterResource)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs ClusterResource, decodeClusterResource, defaultClusterResource, encodeClusterResource, fieldNumbersClusterResource

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `ClusterResource`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersClusterResource : ClusterResource -> Int
fieldNumbersClusterResource n_ =
    case n_ of
        CLUSTERRESOURCEBROWSER ->
            0

        ClusterResourceUnrecognized_ m_ ->
            m_


{-| Default for ClusterResource. Should only be used for 'required' decoders as an initial value.

-}
defaultClusterResource : ClusterResource
defaultClusterResource =
    CLUSTERRESOURCEBROWSER


{-| Declares how to encode a `ClusterResource` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeClusterResource : ClusterResource -> Protobuf.Encode.Encoder
encodeClusterResource value =
    Protobuf.Encode.int32 <|
        case value of
            CLUSTERRESOURCEBROWSER ->
                0

            ClusterResourceUnrecognized_ i ->
                i


{-| Declares how to decode a `ClusterResource` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeClusterResource : Protobuf.Decode.Decoder ClusterResource
decodeClusterResource =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        CLUSTERRESOURCEBROWSER

                    _ ->
                        ClusterResourceUnrecognized_ i
            )


{-| `ClusterResource` enumeration

-}
type ClusterResource
    = CLUSTERRESOURCEBROWSER
    | ClusterResourceUnrecognized_ Int
