{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.CustomHomePage exposing (Target)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Target

-}

import Proto.Rellm.Internals_


{-| ## Options

### Tab

 What `/` renders. Only `HOME_TAB` (the default, combined Events+Posts feed), `EVENTS_TAB`,
 or `POSTS_TAB` are valid here -- never `PEOPLE_TAB`/`ABOUT_TAB`.


### PostId

 Renders a specific Post at `/` instead (e.g. for a custom business site's landing page).


-}
type alias Target =
    Proto.Rellm.Internals_.Proto__Rellm__CustomHomePage__Target__Target
