{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.SyncDestination exposing (Configuration)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Configuration

-}

import Proto.Rellm.Internals_


{-| ## Options

### FacebookPage

 A connected Facebook Page to post Occasions/Posts to.


### InstagramAccount

 A connected Instagram Business/Creator account to post Occasions/Posts to.


### MastodonAccount

 A connected Mastodon account to post Occasions/Posts to.


### BlueskyAccount

 A connected Bluesky account to post Occasions/Posts to.


### XTwitterAccount

 A connected X (Twitter) account to post Occasions/Posts to.


### ThreadsAccount

 A connected Threads account to post Occasions/Posts to.


-}
type alias Configuration =
    Proto.Rellm.Internals_.Proto__Rellm__SyncDestination__Configuration__Configuration
