{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.VerificationAPI exposing (VerificationAPI(..), decodeVerificationAPI, defaultVerificationAPI, encodeVerificationAPI, fieldNumbersVerificationAPI)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs VerificationAPI, decodeVerificationAPI, defaultVerificationAPI, encodeVerificationAPI, fieldNumbersVerificationAPI

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `VerificationAPI`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersVerificationAPI : VerificationAPI -> Int
fieldNumbersVerificationAPI n_ =
    case n_ of
        VERIFICATIONAPITWILIO ->
            0

        VERIFICATIONAPIBIRD ->
            1

        VerificationAPIUnrecognized_ m_ ->
            m_


{-| Default for VerificationAPI. Should only be used for 'required' decoders as an initial value.

-}
defaultVerificationAPI : VerificationAPI
defaultVerificationAPI =
    VERIFICATIONAPITWILIO


{-| Declares how to encode a `VerificationAPI` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeVerificationAPI : VerificationAPI -> Protobuf.Encode.Encoder
encodeVerificationAPI value =
    Protobuf.Encode.int32 <|
        case value of
            VERIFICATIONAPITWILIO ->
                0

            VERIFICATIONAPIBIRD ->
                1

            VerificationAPIUnrecognized_ i ->
                i


{-| Declares how to decode a `VerificationAPI` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeVerificationAPI : Protobuf.Decode.Decoder VerificationAPI
decodeVerificationAPI =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        VERIFICATIONAPITWILIO

                    1 ->
                        VERIFICATIONAPIBIRD

                    _ ->
                        VerificationAPIUnrecognized_ i
            )


{-| `VerificationAPI` enumeration

-}
type VerificationAPI
    = VERIFICATIONAPITWILIO
    | VERIFICATIONAPIBIRD
    | VerificationAPIUnrecognized_ Int
