{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.EventSyncDestination.Configuration exposing (Configuration(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `events.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Configuration

-}


{-| ## Options

### FacebookPage

 A connected Facebook Page to post EventInstances to.


-}
type Configuration a0
    = FacebookPage a0
