#!/usr/bin/env sh

# Paths assume pwd is directory of build script.
cd "$(dirname "$0")"

echo "#-----------------------------------------------------------------------" && \
echo "# Building for Web" && \
echo "#-----------------------------------------------------------------------" && \
flutter build web --web-renderer html --release | sed 's/.*/\[Web\] &/'
# echo "Copying build..." && \
# cp -r build/web/* ../beatscratch-page/app-staging && \
# echo "Web app built to app-staging! Manually copy to prod app and/or deploy to beatscratch.io"
# flutter build web --dart-define=FLUTTER_WEB_USE_SKIA=true --release | sed 's/.*/\[Web\] &/' && \
# echo "Copying build..." && \
# cp -r build/web/* ../beatscratch-page/app-staging-skia && \
# echo "Web app built to app-staging with FLUTTER_WEB_USE_SKIA=true! Manually copy to prod app and/or deploy to beatscratch.io"
