name: jonline
description: Flutter client for Jonline.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+125

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.2
  protobuf: ^2.1.0
  provider: ^6.0.3
  auto_route: ^5.0.1
  build_runner:
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  implicitly_animated_reorderable_list_2: ^0.4.4
  collection: ^1.16.0
  flutter_markdown: ^0.6.10+5
  flutter_link_previewer: ^3.0.1
  url_launcher: ^6.1.5
  link_preview_generator: ^1.2.0
  flutter_staggered_grid_view: ^0.6.2
  scrolls_to_top: ^1.1.1
  native_device_orientation: ^1.1.4
  any_link_preview: ^2.0.9
  get_storage: ^2.0.3
  intl: ^0.17.0
  flutter_colorpicker: ^1.0.3
  multi_select_flutter: ^4.1.2
  recase: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
