apiVersion: v1
kind: Service
metadata:
  name: jonline-tonic
  labels:
    app: jonline-tonic
spec:
  ports:
    - port: 50051
  selector:
    app: jonline-tonic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jonline-tonic
  labels:
    app: jonline-tonic
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jonline-tonic
  template:
    metadata:
      labels:
        app: jonline-tonic
    spec:
      containers:
        - image: docker.io/jonlatane/jonline-tonic:0.1.0
          name: jonline-tonic
          env:
            - name: DATABASE_URL
              value: postgres://admin:password@db/books
          ports:
            - containerPort: 50051
              name: jonline-tonic
