name: jonline
description: Flutter client for Jonline.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+180

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.0.2
  protobuf: ^2.1.0
  provider: ^6.0.3
  auto_route: ^5.0.1
  build_runner:
  shared_preferences: ^2.0.15
  uuid: ^3.0.6
  implicitly_animated_reorderable_list_2: #^0.4.4
    git:
      url: https://github.com/JonLatane/implicitly_animated_reorderable_list_2.git
      ref: master # branch name
  collection: ^1.16.0
  flutter_markdown: ^0.6.10+5
  flutter_link_previewer: ^3.0.1
  url_launcher: ^6.1.5
  link_preview_generator: ^1.2.0
  flutter_staggered_grid_view: ^0.6.2
  scrolls_to_top: ^1.1.1
  native_device_orientation: ^1.1.4
  any_link_preview: ^2.0.9
  get_storage: ^2.0.3
  intl: ^0.17.0
  flutter_colorpicker: ^1.0.3
  multi_select_flutter: ^4.1.2
  recase: ^4.1.0
  flutter_reorderable_grid_view: ^3.1.3
  iconify_flutter: ^0.0.5
  window_manager: ^0.2.7
  image: ^3.2.2
  http: ^0.13.5
  # smooth: 
  #   path: ../../flutter_smooth/packages/smooth

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.1
  # smooth_dev: #/Users/jonlatane/Development/flutter_smooth/packages/smooth_dev
  #   path: ../../flutter_smooth/packages/smooth_dev

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Thin.otf
          weight: 100
        - asset: fonts/PublicSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/PublicSans-ExtraLight.otf
          weight: 200
        - asset: fonts/PublicSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/PublicSans-Light.otf
          weight: 300
        - asset: fonts/PublicSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/PublicSans-Regular.otf
          weight: 400
        - asset: fonts/PublicSans-Italic.otf
          weight: 400
          style: italic
        - asset: fonts/PublicSans-Medium.otf
          weight: 500
        - asset: fonts/PublicSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/PublicSans-SemiBold.otf
          weight: 600
        - asset: fonts/PublicSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/PublicSans-Bold.otf
          weight: 700
        - asset: fonts/PublicSans-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/PublicSans-ExtraBold.otf
          weight: 800
        - asset: fonts/PublicSans-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: fonts/PublicSans-Black.otf
          weight: 900
        - asset: fonts/PublicSans-BlackItalic.otf
          weight: 900
          style: italic
