[package]
name = "jonline"
version = "0.1.4"
edition = "2021"

authors = ["Jon Latané <jonlatane@gmail.com>"]

license = "GPL-3.0"
repository = "https://github.com/jonlatane/jonline"
description = "Backend of Jonline"
default-run = "jonline"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [workspace]

[dependencies]
tonic = { version = "0.7.1", features = ["tls"] }
tonic-reflection = "0.4.0"
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread"] }
prost = "0.10.1"
prost-types = "0.10.1"
diesel = { version = "1.4.8", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
bcrypt = "0.13.0"
bs58 = "0.4.0"
ring = "0.16.20"
# serde = { version = "1.0.138", features = ["derive"] }

[build-dependencies]
tonic-build = "0.7.2"
