[package]
name = "jonline"
version = "0.1.72"
edition = "2021"

authors = ["Jon Latané <jonlatane@gmail.com>"]

license = "GPL-3.0"
repository = "https://github.com/jonlatane/jonline"
description = "Backend of Jonline"
default-run = "jonline"

[dependencies]
tokio = { version = "1.20.0", features = ["macros", "rt-multi-thread"] }
tonic = { version = "0.8.1", features = ["tls", "tls-roots", "tls-webpki-roots", "gzip"] }
tonic-reflection = "0.5.0"
tonic-web = "0.4.0"
rocket = { version= "0.5.0-rc.2", features = [ "tls" ] }
futures = "0.3.24"
prost = "0.11.0"
prost-types = { version = "0.11.1", features = ["std"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4.0"
dotenv = "0.15.0"
bcrypt = "0.13.0"
bs58 = "0.4.0"
ring = "0.16.20"
regex = "1.6.0"

# webscreenshot = "0.2.2"
headless_chrome = { git = "https://github.com/atroche/rust-headless-chrome", features = ["fetch"], rev = "f8012ec4ed867ccc0efa6b262723363afd775011" }
anyhow = "1.0.65"

# security fixes
websocket = "0.26.5"
which = "4.3.0"

[build-dependencies]
tonic-build = "0.8.0"
