{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.EventAttendance.Attendee exposing (Attendee(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `events.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Attendee

-}


{-| ## Options

### UserAttendee

 If the attendance is non-anonymous, core data about the user.


### AnonymousAttendee

 If the attendance is anonymous, core data about the anonymous attendee.


-}
type Attendee a0 a1
    = UserAttendee a0
    | AnonymousAttendee a1
