#!/usr/bin/env bash
# One-shot rename of the "Jonline" project/protocol to "Rellm".
#
# This is a *record* of the mechanical part of the rename (run once, from the
# `rename-to-rellm` branch, from the repo root) -- kept around in case a
# similar bulk rename is ever needed again, or a stray reference turns up
# later and needs the same treatment.
#
# What it does NOT touch: the literal domain "jonline.io" (and its
# capitalized display form "Jonline.io") stay exactly as-is everywhere --
# that's a live, unrelated hostname, not the project name. Everything else
# spelling "jonline"/"Jonline"/"JONLINE" is assumed to be the project name and
# is rewritten to "rellm"/"Rellm"/"RELLM".
#
# Excluded from the blanket text substitution (handled separately, see
# below): lockfiles (regenerated by the real package managers instead of
# hand-edited) and generated protobuf bindings (regenerated fresh by
# `make protos` after protos/jonline.proto is renamed, rather than edited
# in place under their old names).
set -euo pipefail
cd "$(dirname "$0")/.."

# --- 1. Delete generated protobuf bindings tied to the old package name.
# `make protos` (run later, by hand, after this script) regenerates these
# under their new "Rellm"-named paths.
git rm -rq --ignore-unmatch \
  frontends/elm-spa/src/Proto/Jonline.elm \
  frontends/elm-spa/src/Proto/Jonline \
  frontends/flutter/lib/generated/jonline.pb.dart \
  frontends/flutter/lib/generated/jonline.pbenum.dart \
  frontends/flutter/lib/generated/jonline.pbgrpc.dart \
  frontends/flutter/lib/generated/jonline.pbjson.dart \
  frontends/tamagui/packages/api/generated/jonline.ts

# --- 2. Blanket case-preserving text substitution across all other tracked
# text files, protecting the literal jonline.io / Jonline.io / JONLINE.IO
# domain strings.
EXCLUDE_REGEX='^(backend/Cargo\.lock|frontends/tamagui/yarn\.lock|frontends/tamagui/package-lock\.json)$'

git ls-files \
  | grep -vE "$EXCLUDE_REGEX" \
  | python3 "$(dirname "$0")/rename_jonline_to_rellm.py"

# --- 3. Fix up the two filenames that reorder rather than substring-replace
# (docs/homebrew_jonline.sh -> docs/rellm_homebrew.sh, not homebrew_rellm.sh),
# in file contents (the blanket pass above already turned "jonline" into
# "rellm" in place, so we're fixing word order here, not casing).
git ls-files -z \
  | grep -vzE "$EXCLUDE_REGEX" \
  | xargs -0 perl -pi -e '
      s/homebrew_rellm\.sh/rellm_homebrew.sh/g;
      s/linux_rellm\.sh/rellm_linux.sh/g;
    '

# --- 4. Explicit path renames (git mv). Do this after the content pass so
# git mv operates on the (still old-named) paths one last time.
git mv protos/jonline.proto protos/rellm.proto
git mv backend/src/jonline_service.rs backend/src/rellm_service.rs
git mv backend/src/web/jonline_path.rs backend/src/web/rellm_path.rs
git mv docs/homebrew_jonline.sh docs/rellm_homebrew.sh
git mv docs/linux_jonline.sh docs/rellm_linux.sh
git mv deploys/ingress/k8s/jonline-routes.template.yaml deploys/ingress/k8s/rellm-routes.template.yaml
git mv frontends/flutter/android/app/src/main/kotlin/com/example/jonline \
       frontends/flutter/android/app/src/main/kotlin/com/example/rellm

echo "Done. Now run 'make' (protos+docs+graphs), then 'make test', and review the diff."
