{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.CustomNavigationTab.Icon exposing (Icon(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Icon

-}


{-| ## Options

### EmojiIcon

 Emoji shown as the tab's icon (e.g. "🎪").


### IconMediaId

 Media ID (see `Media` APIs) of an image shown as the tab's icon.


-}
type Icon a0 a1
    = EmojiIcon a0
    | IconMediaId a1
