CREATE TABLE push_tokens(
  id BIGSERIAL PRIMARY KEY,
  token VARCHAR NOT NULL UNIQUE,
  user_id BIGINT NULL REFERENCES users(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE push_token_posts(
  id BIGSERIAL PRIMARY KEY,
  push_token_id BIGINT NOT NULL REFERENCES push_tokens(id),
  post_id BIGINT NOT NULL REFERENCES posts(id),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
