ALTER TABLE event_sync_sources RENAME TO sync_sources;
ALTER SEQUENCE event_sync_sources_id_seq RENAME TO sync_sources_id_seq;
ALTER TABLE sync_sources RENAME CONSTRAINT event_sync_sources_pkey TO sync_sources_pkey;
ALTER TABLE sync_sources RENAME CONSTRAINT event_sync_sources_user_id_fkey TO sync_sources_user_id_fkey;
ALTER INDEX idx_event_sync_sources_user_id RENAME TO idx_sync_sources_user_id;

ALTER TABLE sync_sources ADD COLUMN post_count BIGINT NOT NULL DEFAULT 0;

ALTER TABLE events RENAME COLUMN event_sync_source_id TO sync_source_id;
ALTER TABLE events RENAME CONSTRAINT events_event_sync_source_id_fkey TO events_sync_source_id_fkey;
ALTER INDEX idx_events_event_sync_source_id RENAME TO idx_events_sync_source_id;

ALTER TABLE event_instances RENAME COLUMN event_sync_source_instance_id TO sync_source_instance_id;
ALTER INDEX idx_event_instances_event_sync_source_instance_id RENAME TO idx_event_instances_sync_source_instance_id;
