{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.GenerateMediaRequest.Target exposing (Target(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `ai_model_providers.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Target

-}


{-|  What, if anything, the generated image should be attached to (as the *first* item in its `media` list) once
 generated, and whose content gets folded into `user_prompt` as context -- see this message's own doc. Leave
 unset to just generate/store the image in the current user's own Media (as `MyMediaPanel` shows), without
 attaching it to anything.


## Options

### PostId

 Attach to (and use the content of) this Post. Caller must be its author, or an Admin.


### EventInstanceId

 Attach to (and use the content of) this EventInstance's parent Event's own Post -- named by
 EventInstance, not Event, since that's what a viewer is actually looking at (and what gives
 the generated prompt its date/time/location context, the same way
 [`SyncEventInstance`](#grpc-api-SyncEventInstance) does). Caller must be the Event's own
 Post's author, or hold `MODERATE_POSTS`/`MODERATE_EVENTS`, or be an Admin.


-}
type Target a0 a1
    = PostId a0
    | EventInstanceId a1
