apiVersion: v1
kind: Service
metadata:
  name: jonline-lb
  labels:
    app: jonline-lb
spec:
  # Update this to use an external LoadBalancer instead of internal ClusterIP
  # once this seems to be working.
  type: ClusterIP
  # type: LoadBalancer
  selector:
    app: jonline-lb
  ports:
    - name: grpc
      protocol: TCP
      port: 27707
      targetPort: 27707
    - name: web-secure
      protocol: TCP
      port: 443
      targetPort: 443
    - name: web-insecure-1
      protocol: TCP
      port: 80
      targetPort: 80
    - name: web-insecure-2
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jonline-lb
  labels:
    app: jonline-lb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jonline-lb
  template:
    metadata:
      labels:
        app: jonline-lb
    spec:
      serviceAccountName: jonline-lb
      containers:
        - image: docker.io/jonlatane/jbl:0.2.533
          name: jonline-lb
          env:
            - name: SERVERS
              valueFrom:
                configMapKeyRef:
                  name: jonline-lb-config
                  key: servers
            - name: NO_CERTS
              value: "true"

          ports:
            - containerPort: 27707
              protocol: TCP
              name: jonline
            - containerPort: 443
              protocol: TCP
              name: jonline-web-s
            - containerPort: 80
              protocol: TCP
              name: jonline-web-i1
            - containerPort: 8000
              protocol: TCP
              name: jonline-web-i2
