apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-preview-images
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: generate-preview-images
              image: docker.io/jonlatane/rellm_preview_generator:0.5.553
              imagePullPolicy: IfNotPresent
              env:
                - name: DATABASE_URL
                  value: postgres://admin:secure_password1@rellm-postgres/rellm
                - name: MINIO_ENDPOINT
                  value: http://rellm-minio:9000
                - name: MINIO_REGION
                  value: ""
                - name: MINIO_BUCKET
                  value: rellm
                - name: MINIO_ACCESS_KEY
                  value: minio
                - name: MINIO_SECRET_KEY
                  value: minio123
                - name: RUST_BACKTRACE
                  value: full
                - name: RUST_LOG
                  value: headless_chrome=trace
              command:
                - /opt/generate_preview_images
          restartPolicy: Never
