{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.AIModelProvider.Provider exposing (Provider(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `ai_model_providers.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Provider

-}


{-|  Identifies which external AI service this provider connects to, and carries that service's credentials. Only
 one variant may be set at a time. Only the `gemini_credentials` variant is currently accepted by
 [`CreateAIModelProvider`](#grpc-api-CreateAIModelProvider)/[`UpdateAIModelProvider`](#grpc-api-UpdateAIModelProvider) --
 see each credentials message below for why the actual key/secret is never sent back in a response.


## Options

### GeminiCredentials

 A Google Gemini API connection (see `ai.google.dev/gemini-api` -- planned use is its image generation
 endpoint, for generating Event posters). The only variant currently creatable.


### OpenaiCredentials

 An OpenAI API connection. *Not yet creatable.*


### AnthropicCredentials

 An Anthropic API connection. *Not yet creatable.*


-}
type Provider a0 a1 a2
    = GeminiCredentials a0
    | OpenaiCredentials a1
    | AnthropicCredentials a2
