{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.AIModelProvider.Provider exposing (Provider(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `ai_model_providers.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Provider

-}


{-|  Identifies which external AI service this provider connects to, and carries that service's credentials. Only
 one variant may be set at a time. The `gemini_credentials`/`openai_credentials` variants are accepted by
 [`CreateAIModelProvider`](#grpc-api-CreateAIModelProvider)/[`UpdateAIModelProvider`](#grpc-api-UpdateAIModelProvider) --
 see each credentials message below for why the actual key/secret is never sent back in a response.


## Options

### GeminiCredentials

 A Google Gemini API connection (see `ai.google.dev/gemini-api`), used for image generation/editing (e.g.
 generating Event posters) via its Interactions API.


### OpenaiCredentials

 An OpenAI API connection (see `platform.openai.com/docs/guides/image-generation`), used for image
 generation/editing via its Images API (GPT Image models).


### AnthropicCredentials

 An Anthropic API connection. *Not yet creatable* -- Anthropic doesn't offer an image generation API.


-}
type Provider a0 a1 a2
    = GeminiCredentials a0
    | OpenaiCredentials a1
    | AnthropicCredentials a2
