{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.SyncDestination.Configuration exposing (Configuration(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `sync.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Configuration

-}


{-| ## Options

### FacebookPage

 A connected Facebook Page to post Occasions/Posts to.


### InstagramAccount

 A connected Instagram Business/Creator account to post Occasions/Posts to.


### MastodonAccount

 A connected Mastodon account to post Occasions/Posts to.


### BlueskyAccount

 A connected Bluesky account to post Occasions/Posts to.


### XTwitterAccount

 A connected X (Twitter) account to post Occasions/Posts to.


### ThreadsAccount

 A connected Threads account to post Occasions/Posts to.


-}
type Configuration a0 a1 a2 a3 a4 a5
    = FacebookPage a0
    | InstagramAccount a1
    | MastodonAccount a2
    | BlueskyAccount a3
    | XTwitterAccount a4
    | ThreadsAccount a5
