{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Rellm.SyncSource.Configuration exposing (Configuration(..))

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `sync.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Configuration

-}


{-| ## Options

### IcsSubscriptionUrl

 The iCal subscription URL for the calendar sync. Creates/updates Events/Occasions.


### RssSubscriptionUrl

 The RSS subscription URL for the feed sync. Creates/updates plain Posts.


### AtomSubscriptionUrl

 The Atom subscription URL for the feed sync. Creates/updates plain Posts.


-}
type Configuration a0 a1 a2
    = IcsSubscriptionUrl a0
    | RssSubscriptionUrl a1
    | AtomSubscriptionUrl a2
