{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.AIModelCapability exposing (AIModelCapability(..), decodeAIModelCapability, defaultAIModelCapability, encodeAIModelCapability, fieldNumbersAIModelCapability)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `ai_model_providers.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs AIModelCapability, decodeAIModelCapability, defaultAIModelCapability, encodeAIModelCapability, fieldNumbersAIModelCapability

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `AIModelCapability`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersAIModelCapability : AIModelCapability -> Int
fieldNumbersAIModelCapability n_ =
    case n_ of
        AIMODELCAPABILITYUNKNOWN ->
            0

        AIMODELCAPABILITYTEXTGENERATION ->
            1

        AIMODELCAPABILITYIMAGEGENERATION ->
            2

        AIMODELCAPABILITYIMAGEEDITING ->
            3

        AIModelCapabilityUnrecognized_ m_ ->
            m_


{-| Default for AIModelCapability. Should only be used for 'required' decoders as an initial value.

-}
defaultAIModelCapability : AIModelCapability
defaultAIModelCapability =
    AIMODELCAPABILITYUNKNOWN


{-| Declares how to encode a `AIModelCapability` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeAIModelCapability : AIModelCapability -> Protobuf.Encode.Encoder
encodeAIModelCapability value =
    Protobuf.Encode.int32 <|
        case value of
            AIMODELCAPABILITYUNKNOWN ->
                0

            AIMODELCAPABILITYTEXTGENERATION ->
                1

            AIMODELCAPABILITYIMAGEGENERATION ->
                2

            AIMODELCAPABILITYIMAGEEDITING ->
                3

            AIModelCapabilityUnrecognized_ i ->
                i


{-| Declares how to decode a `AIModelCapability` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeAIModelCapability : Protobuf.Decode.Decoder AIModelCapability
decodeAIModelCapability =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        AIMODELCAPABILITYUNKNOWN

                    1 ->
                        AIMODELCAPABILITYTEXTGENERATION

                    2 ->
                        AIMODELCAPABILITYIMAGEGENERATION

                    3 ->
                        AIMODELCAPABILITYIMAGEEDITING

                    _ ->
                        AIModelCapabilityUnrecognized_ i
            )


{-| `AIModelCapability` enumeration

-}
type AIModelCapability
    = AIMODELCAPABILITYUNKNOWN
    | AIMODELCAPABILITYTEXTGENERATION
    | AIMODELCAPABILITYIMAGEGENERATION
    | AIMODELCAPABILITYIMAGEEDITING
    | AIModelCapabilityUnrecognized_ Int
