{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.AttendanceStatus exposing (AttendanceStatus(..), decodeAttendanceStatus, defaultAttendanceStatus, encodeAttendanceStatus, fieldNumbersAttendanceStatus)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `events.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs AttendanceStatus, decodeAttendanceStatus, defaultAttendanceStatus, encodeAttendanceStatus, fieldNumbersAttendanceStatus

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `AttendanceStatus`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersAttendanceStatus : AttendanceStatus -> Int
fieldNumbersAttendanceStatus n_ =
    case n_ of
        INTERESTED ->
            0

        REQUESTED ->
            1

        GOING ->
            2

        NOTGOING ->
            3

        AttendanceStatusUnrecognized_ m_ ->
            m_


{-| Default for AttendanceStatus. Should only be used for 'required' decoders as an initial value.

-}
defaultAttendanceStatus : AttendanceStatus
defaultAttendanceStatus =
    INTERESTED


{-| Declares how to encode a `AttendanceStatus` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeAttendanceStatus : AttendanceStatus -> Protobuf.Encode.Encoder
encodeAttendanceStatus value =
    Protobuf.Encode.int32 <|
        case value of
            INTERESTED ->
                0

            REQUESTED ->
                1

            GOING ->
                2

            NOTGOING ->
                3

            AttendanceStatusUnrecognized_ i ->
                i


{-| Declares how to decode a `AttendanceStatus` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeAttendanceStatus : Protobuf.Decode.Decoder AttendanceStatus
decodeAttendanceStatus =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        INTERESTED

                    1 ->
                        REQUESTED

                    2 ->
                        GOING

                    3 ->
                        NOTGOING

                    _ ->
                        AttendanceStatusUnrecognized_ i
            )


{-| `AttendanceStatus` enumeration

-}
type AttendanceStatus
    = INTERESTED
    | REQUESTED
    | GOING
    | NOTGOING
    | AttendanceStatusUnrecognized_ Int
