{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.AuthenticationFeature exposing (AuthenticationFeature(..), decodeAuthenticationFeature, defaultAuthenticationFeature, encodeAuthenticationFeature, fieldNumbersAuthenticationFeature)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs AuthenticationFeature, decodeAuthenticationFeature, defaultAuthenticationFeature, encodeAuthenticationFeature

@docs fieldNumbersAuthenticationFeature

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `AuthenticationFeature`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersAuthenticationFeature : AuthenticationFeature -> Int
fieldNumbersAuthenticationFeature n_ =
    case n_ of
        AUTHENTICATIONFEATUREUNKNOWN ->
            0

        CREATEACCOUNT ->
            1

        LOGIN ->
            2

        AuthenticationFeatureUnrecognized_ m_ ->
            m_


{-| Default for AuthenticationFeature. Should only be used for 'required' decoders as an initial value.

-}
defaultAuthenticationFeature : AuthenticationFeature
defaultAuthenticationFeature =
    AUTHENTICATIONFEATUREUNKNOWN


{-| Declares how to encode a `AuthenticationFeature` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeAuthenticationFeature : AuthenticationFeature -> Protobuf.Encode.Encoder
encodeAuthenticationFeature value =
    Protobuf.Encode.int32 <|
        case value of
            AUTHENTICATIONFEATUREUNKNOWN ->
                0

            CREATEACCOUNT ->
                1

            LOGIN ->
                2

            AuthenticationFeatureUnrecognized_ i ->
                i


{-| Declares how to decode a `AuthenticationFeature` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeAuthenticationFeature : Protobuf.Decode.Decoder AuthenticationFeature
decodeAuthenticationFeature =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        AUTHENTICATIONFEATUREUNKNOWN

                    1 ->
                        CREATEACCOUNT

                    2 ->
                        LOGIN

                    _ ->
                        AuthenticationFeatureUnrecognized_ i
            )


{-| `AuthenticationFeature` enumeration

-}
type AuthenticationFeature
    = AUTHENTICATIONFEATUREUNKNOWN
    | CREATEACCOUNT
    | LOGIN
    | AuthenticationFeatureUnrecognized_ Int
