{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.CalendarDisplayMode exposing (CalendarDisplayMode(..), decodeCalendarDisplayMode, defaultCalendarDisplayMode, encodeCalendarDisplayMode, fieldNumbersCalendarDisplayMode)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs CalendarDisplayMode, decodeCalendarDisplayMode, defaultCalendarDisplayMode, encodeCalendarDisplayMode

@docs fieldNumbersCalendarDisplayMode

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `CalendarDisplayMode`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersCalendarDisplayMode : CalendarDisplayMode -> Int
fieldNumbersCalendarDisplayMode n_ =
    case n_ of
        CALENDARDISPLAYWEEK ->
            0

        CALENDARDISPLAYMONTH ->
            1

        CALENDARDISPLAYDAY ->
            3

        CalendarDisplayModeUnrecognized_ m_ ->
            m_


{-| Default for CalendarDisplayMode. Should only be used for 'required' decoders as an initial value.

-}
defaultCalendarDisplayMode : CalendarDisplayMode
defaultCalendarDisplayMode =
    CALENDARDISPLAYWEEK


{-| Declares how to encode a `CalendarDisplayMode` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeCalendarDisplayMode : CalendarDisplayMode -> Protobuf.Encode.Encoder
encodeCalendarDisplayMode value =
    Protobuf.Encode.int32 <|
        case value of
            CALENDARDISPLAYWEEK ->
                0

            CALENDARDISPLAYMONTH ->
                1

            CALENDARDISPLAYDAY ->
                3

            CalendarDisplayModeUnrecognized_ i ->
                i


{-| Declares how to decode a `CalendarDisplayMode` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeCalendarDisplayMode : Protobuf.Decode.Decoder CalendarDisplayMode
decodeCalendarDisplayMode =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        CALENDARDISPLAYWEEK

                    1 ->
                        CALENDARDISPLAYMONTH

                    3 ->
                        CALENDARDISPLAYDAY

                    _ ->
                        CalendarDisplayModeUnrecognized_ i
            )


{-| `CalendarDisplayMode` enumeration

-}
type CalendarDisplayMode
    = CALENDARDISPLAYWEEK
    | CALENDARDISPLAYMONTH
    | CALENDARDISPLAYDAY
    | CalendarDisplayModeUnrecognized_ Int
