{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.CustomNavigationTab exposing (Target)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: ``

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Target

-}

import Proto.Jonline.Internals_


{-| ## Options

### Tab

 Links to one of the app's predefined tabs/pages.


### PostId

 Links to a specific Post (e.g. for a custom business site's page).


-}
type alias Target =
    Proto.Jonline.Internals_.Proto__Jonline__CustomNavigationTab__Target__Target
