{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.EventListingType exposing (EventListingType(..), decodeEventListingType, defaultEventListingType, encodeEventListingType, fieldNumbersEventListingType)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `events.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs EventListingType, decodeEventListingType, defaultEventListingType, encodeEventListingType, fieldNumbersEventListingType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `EventListingType`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersEventListingType : EventListingType -> Int
fieldNumbersEventListingType n_ =
    case n_ of
        ALLACCESSIBLEEVENTS ->
            0

        FOLLOWINGEVENTS ->
            1

        MYGROUPSEVENTS ->
            2

        DIRECTEVENTS ->
            3

        EVENTSPENDINGMODERATION ->
            4

        GROUPEVENTS ->
            10

        GROUPEVENTSPENDINGMODERATION ->
            11

        NEWLYADDEDEVENTS ->
            20

        EventListingTypeUnrecognized_ m_ ->
            m_


{-| Default for EventListingType. Should only be used for 'required' decoders as an initial value.

-}
defaultEventListingType : EventListingType
defaultEventListingType =
    ALLACCESSIBLEEVENTS


{-| Declares how to encode a `EventListingType` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeEventListingType : EventListingType -> Protobuf.Encode.Encoder
encodeEventListingType value =
    Protobuf.Encode.int32 <|
        case value of
            ALLACCESSIBLEEVENTS ->
                0

            FOLLOWINGEVENTS ->
                1

            MYGROUPSEVENTS ->
                2

            DIRECTEVENTS ->
                3

            EVENTSPENDINGMODERATION ->
                4

            GROUPEVENTS ->
                10

            GROUPEVENTSPENDINGMODERATION ->
                11

            NEWLYADDEDEVENTS ->
                20

            EventListingTypeUnrecognized_ i ->
                i


{-| Declares how to decode a `EventListingType` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeEventListingType : Protobuf.Decode.Decoder EventListingType
decodeEventListingType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        ALLACCESSIBLEEVENTS

                    1 ->
                        FOLLOWINGEVENTS

                    2 ->
                        MYGROUPSEVENTS

                    3 ->
                        DIRECTEVENTS

                    4 ->
                        EVENTSPENDINGMODERATION

                    10 ->
                        GROUPEVENTS

                    11 ->
                        GROUPEVENTSPENDINGMODERATION

                    20 ->
                        NEWLYADDEDEVENTS

                    _ ->
                        EventListingTypeUnrecognized_ i
            )


{-| `EventListingType` enumeration

-}
type EventListingType
    = ALLACCESSIBLEEVENTS
    | FOLLOWINGEVENTS
    | MYGROUPSEVENTS
    | DIRECTEVENTS
    | EVENTSPENDINGMODERATION
    | GROUPEVENTS
    | GROUPEVENTSPENDINGMODERATION
    | NEWLYADDEDEVENTS
    | EventListingTypeUnrecognized_ Int
