{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}


module Proto.Jonline.EventSyncSource exposing (Configuration)

{-| This file was automatically generated by

  - [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
  - `protoc` 5.29.3
  - the following specification files: \`\`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Configuration

-}

import Proto.Jonline.Internals_


{-|


## Options


### IcsSubscriptionUrl

The iCal subscription URL for the calendar sync.

-}
type alias Configuration =
    Proto.Jonline.Internals_.Proto__Jonline__EventSyncSource__Configuration__Configuration
