{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.GroupListingType exposing (GroupListingType(..), decodeGroupListingType, defaultGroupListingType, encodeGroupListingType, fieldNumbersGroupListingType)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `groups.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs GroupListingType, decodeGroupListingType, defaultGroupListingType, encodeGroupListingType, fieldNumbersGroupListingType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `GroupListingType`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersGroupListingType : GroupListingType -> Int
fieldNumbersGroupListingType n_ =
    case n_ of
        ALLGROUPS ->
            0

        MYGROUPS ->
            1

        REQUESTEDGROUPS ->
            2

        INVITEDGROUPS ->
            3

        GroupListingTypeUnrecognized_ m_ ->
            m_


{-| Default for GroupListingType. Should only be used for 'required' decoders as an initial value.

-}
defaultGroupListingType : GroupListingType
defaultGroupListingType =
    ALLGROUPS


{-| Declares how to encode a `GroupListingType` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeGroupListingType : GroupListingType -> Protobuf.Encode.Encoder
encodeGroupListingType value =
    Protobuf.Encode.int32 <|
        case value of
            ALLGROUPS ->
                0

            MYGROUPS ->
                1

            REQUESTEDGROUPS ->
                2

            INVITEDGROUPS ->
                3

            GroupListingTypeUnrecognized_ i ->
                i


{-| Declares how to decode a `GroupListingType` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeGroupListingType : Protobuf.Decode.Decoder GroupListingType
decodeGroupListingType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        ALLGROUPS

                    1 ->
                        MYGROUPS

                    2 ->
                        REQUESTEDGROUPS

                    3 ->
                        INVITEDGROUPS

                    _ ->
                        GroupListingTypeUnrecognized_ i
            )


{-| `GroupListingType` enumeration

-}
type GroupListingType
    = ALLGROUPS
    | MYGROUPS
    | REQUESTEDGROUPS
    | INVITEDGROUPS
    | GroupListingTypeUnrecognized_ Int
