{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.Jonline exposing (accessToken, configureServer, createAccount, createEvent, createEventSyncDestination, createEventSyncSource, createFollow, createGroup, createGroupPost, createMembership, createPost, defederateProfile, deleteEvent, deleteEventAttendance, deleteEventSyncDestination, deleteEventSyncSource, deleteFollow, deleteGroup, deleteGroupPost, deleteMedia, deleteMembership, deletePost, deleteUser, federateProfile, getCurrentUser, getEventAttendances, getEventSyncDestinations, getEventSyncSources, getEvents, getGroupPosts, getGroups, getMedia, getMembers, getMessages, getPosts, getServerConfiguration, getServiceVersion, getUsers, login, resetData, resetPassword, sendMessage, starPost, syncEventInstance, unstarPost, updateEvent, updateEventSyncDestination, updateEventSyncSource, updateFollow, updateGroup, updateGroupPost, updateMembership, updatePost, updateUser, upsertEventAttendance)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `jonline.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

 [Jonline](https://github.com/JonLatane/jonline) is a social media protocol with support for Users (and Follows), Media, Posts, Events, Groups, and Messages. It is designed to be federated, 
 but does not require federation to be a useful next-gen forum type solution.
 It is designed to be used with a variety of frontends, including web, mobile, and desktop applications. It interoperates across numerous ports, protocols, and formats, including
 gRPC, HTTP, HTTPS, and ICS/iCal, and is designed to link with SMTP via Stalwart (and other SMTP servers/providers), Facebook Page APIs for post ing Events, and more.
 Essentially, your server is your own customizable, self-contained social network.

 Jonline is designed to be easy to run and deploy yourself with a [2 minute setup with Homebrew](#2-minute-startup-with-homebrew) and [3 minute setup on Linux](#3-minute-startup-on-linux),
 [images](https://hub.docker.com/r/jonlatane/jonline/tags) on [DockerHub](https://hub.docker.com/r/jonlatane/jonline_preview_generator/tags) and deployment to your K8s clusters available via
 a simple but powerful `Makefile`-based design language.

 #### Ports
 Jonline servers interact across several ports:
 * [gRPC (27707)](#grpc-api) - The main Jonline gRPC API, typically served from the Jonline. This is the primary port for all Jonline clients. It may or may not be TLS-enabled (443).
      * Clients are expected to negotiate the gRPC host via the [`backend_host` HTTP endpoint (see below)](#http-based-client-host-negotiation-for-external-cdns) on port 80/443.
 * [HTTP (80, 8000, 27705), HTTPS (443)](#http-endpoints) - The main Jonline HTTP API. This is used for some endpoints, including media upload/download, and for negotiating the gRPC host.
      * Port 443 will serve up a secure HTTPS server. If it fails to startup, Jonline handles this gracefully and degrades to plain HTTP.
      * Port 80 will serve up either an unsecured set of Jonline's HTTP endpoints, or a redirect to the HTTPS/443 server if that one launched successfully.
      * Port 8000 *always* serves up an unsecured Jonline UI, in case something goes horribly wrong with 80 and 443. It can probably not be exposed in your load balancer/to the web.
      * Port 27705 is an unsecured HTTP server meant for communication with other non-web facing services on your computer or in your cluster. It should not be exposed to the web.
          * Currently this just has an `/email` endpoint. It is designed for [email support via an integration with Stalwart](https://github.com/JonLatane/jonline/tree/main/deploys/email).

 #### API Design Notes
 ##### Moderation and Visibility
 Jonline APIs are designed to support `Moderation` and `Visibility` controls at the level of individual entities. However, to keep things
 DRY, moderation and visibility controls are only implemented for `User`s, `Media`, `Group`s, and `Post`s.

 `Event`s and future `Post`-like types simply use the same implementation as their contained `Post`s. The intent here is to maximize
 both shared code and implementation robustness.

 ##### Composition Over Inheritance
 Jonline's APIs are designed using composition over inheritance. For instance, an `Event` contains
 a `Post` rather than extending it. This pattern fits well all the way from the data model (very boring, safe, and normalized), 
 through Rust code implementing APIs, to both functional React code and more-OOP Flutter code equally well.

 ##### Predictable Atomicity
 The use of composition over inheritance also means that Jonline APIs can be *predictably* non-atomic based on their compositional structure.
 For instance, `UpdatePost` is fully atomic.

 `UpdateEvent`, however, is non-atomic. Given that an `Event` has a `Post` and many `EventInstance`s, 
 `UpdateEvent` will first update the `Post` atomically (literally calling the `UpdatePost` RPC),
 then the `Event` atomically, and then finally process updates to its `EventInstance`s in a final atomic operation. 

 Because moderation/visibility lives at the `Post` level, this means that a developer error in `UpdateEvents` cannot prevent 
 visibility and moderation changes from being made in Events, even if there are errors elsewhere.
 This should prove a robust pattern for any future entities intended to be shareable at a Group level with visibility and
 moderation controls (for instance, `Sheet`, `SharedExpenseReport`, `SharedCalendar`, etc.). The entire architecture should promote this
 approach to predictable atomicity.

 #### Core Types
 Jonline's data model centers around a handful of top-level types, most of which carry their own
 [`Visibility`](#jonline-Visibility) and [`Moderation`](#jonline-Moderation) state and can be organized into
 [`Group`](#jonline-Group)s.

 ##### User
 A [`User`](#jonline-User) is a Jonline account: username, real name, bio, avatar, contact methods, and
 [`Permission`](#jonline-Permission)s, plus counts (followers, posts, events, etc.) and federation info (see
 [Federated Profiles](#federated-profiles) above). A lighter-weight [`Author`](#jonline-Author) (just ID, username,
 avatar, real name, permissions) is embedded on [`Post`](#jonline-Post)s, [`Message`](#jonline-Message)s, and similar
 content types instead of a full `User`, to keep those payloads small.

 - **Follows**: A [`Follow`](#jonline-Follow) is one `User` following another, optionally subject to the target's moderation
 (i.e. approval). Mutual follows make two users "friends." Follows also drive the `FOLLOWING_POSTS`/`FOLLOWING_EVENTS`
 listing types and `LIMITED`-visibility content.

 - **Memberships**: A [`Membership`](#jonline-Membership) is a `User`'s membership (or pending join request/invitation)
 in a `Group`, tracking the user's `Permission`s within the group plus separate group-side and user-side `Moderation`
 (for join-approval flows). Returned as part of `User`/`Group` payloads, and via `Member` when listing a Group's members.


 - **EventSyncSources**: A `User` can own many [`EventSyncSource`](#jonline-EventSyncSource)s - external calendars to
 pull `Event`s in from, e.g. an iCal subscription. See the Event section below for how these attach to `Event`s.

 - **EventSyncDestinations**: A `User` can also own many [`EventSyncDestination`](#jonline-EventSyncDestination)s -
 external targets to push `EventInstance`s out to, e.g. a connected Facebook Page (configured via
 [`FacebookPage`](#jonline-FacebookPage)). See the Event section below for how these attach to `EventInstance`s.

 ##### Media
 [`Media`](#jonline-Media) represents an uploaded (or server-generated) photo or video. Unlike other types, Media
 content itself is *not* served over gRPC - it's uploaded/downloaded via plain HTTP (`POST`/`GET /media`) - while
 its metadata (content type, name, visibility, moderation) is managed like any other Jonline type. Other messages
 (like `User.avatar`, `Group.avatar`, and `Post.media`) reference Media via the lightweight `MediaReference` type.

 ##### Post
 [`Post`](#jonline-Post) is Jonline's fundamental content/building-block type: it's what actually carries a
 title/link/content body, visibility, and moderation, and is reused (via `PostContext`) as the backing data for
 replies, [`Event`](#jonline-Event)s, and `EventInstance`s alike. Posts can be replied to (threaded via
 `reply_to_post_id`), cross-posted to `Group`s (`GroupPost`), and shared directly with users (`UserPost`).

 - **GroupPosts**: A [`GroupPost`](#jonline-GroupPost) is the cross-posting of a `Post` into a `Group`, carrying the group-specific
 moderation status and who shared it, separately from the Post's own (author-set) visibility/moderation.

 - **UserPosts**: A [`UserPost`](#jonline-UserPost) is a "direct share" of a `Post` to a `User` (see also `DIRECT`
 [`Visibility`](#jonline-Visibility)). Currently unused/unimplemented.

 ##### Event
 An [`Event`](#jonline-Event) is a wrapper for *at least two* `Post`s. It always has its own top-level `Post`
 (`PostContext.EVENT`, holding the event's overall title/description) *and* it must have at least one
 [`EventInstance`](#jonline-EventInstance) (see below), each of which in turn must have its own `Post`
 (`PostContext.EVENT_INSTANCE`, carrying that instance's start/end time, `Location`, and optional per-instance
 title/link/content override). So the smallest possible Event already backs 2 Posts, and events with recurring/multiple
 instances back one Post per instance beyond that.

 - **EventInstances**: An [`EventInstance`](#jonline-EventInstance) is the actual time-boxed occurrence of an `Event` -
 it carries the `starts_at`/`ends_at` timestamps and optional `Location` that the parent `Event` itself does not have.
 An `Event` with zero instances is meaningless (no time or place to attach to), so every `Event` must have at least one.

     - **EventAttendances**: An [`EventAttendance`](#jonline-EventAttendance) (an "RSVP") tracks one attendee's status
     (`INTERESTED`, `REQUESTED`, `GOING`, `NOT_GOING`) for a specific `EventInstance`. Attendees may be logged-in `User`s
     or anonymous (tracked via `AnonymousAttendee` plus an `auth_token`), and are subject to their own `Moderation`,
     independent of the Event's/Instance's own Post moderation.

     - **EventSyncSource**: It's actually the parent `Event` (not the `EventInstance`) that can be synced *in* from a
     user-owned [`EventSyncSource`](#jonline-EventSyncSource) (e.g. an iCal subscription). The relationship is
     1:(0 or 1): a single source can back many synced `Event`s, but each `Event` has *at most one* source it came from
     (`Event.event_sync_source` is a single optional field, not repeated).

     - **EventSyncDestinations**: Conversely, it's each `EventInstance` (not the parent `Event`) that syncs *out* to
     [`EventSyncDestination`](#jonline-EventSyncDestination)s (e.g. connected Facebook Pages). Unlike `EventSyncSource`,
     this is the outlier's counterpart - a many-to-many relationship: each instance may push to several destinations
     at once, tracked per-destination via the repeated `EventInstance.sync_destinations`
     (each a [`EventInstanceSyncDestination`](#jonline-EventInstanceSyncDestination), carrying the destination's
     resulting post ID/URL and last-synced time).

 ##### Group
 A [`Group`](#jonline-Group) organizes `User`s, `Post`s, and `Event`s together under shared visibility, moderation,
 and permission defaults.

 - **Memberships**: A [`Membership`](#jonline-Membership) is a `User`'s membership (or pending join request/invitation)
 in a `Group`, tracking the user's `Permission`s within the group plus separate group-side and user-side `Moderation`
 (for join-approval flows). Returned as part of `User`/`Group` payloads, and via `Member` when listing a Group's members.

 - **GroupPosts**: A [`GroupPost`](#jonline-GroupPost) is the cross-posting of a `Post` into a `Group`, carrying the group-specific
 moderation status and who shared it, separately from the Post's own (author-set) visibility/moderation.

 ##### Message
 [`Message`](#jonline-Message) is Jonline's "low trust" messaging/email system, meant to let strangers on a server
 make first contact (e.g. via email, with no account required) before moving to a more trusted channel. Admins have
 open access to all Messages on a server.

 - **MessagingGroup**: A [`MessagingGroup`](#jonline-MessagingGroup) is the set of participants in a Message conversation. Every `Message`
 belongs to one; if a client wasn't a visible recipient (e.g. they were BCC'ed), the `Message` they receive omits it.

 #### Authentication
 Jonline uses a standard OAuth2 flow (over gRPC) for authentication, with rotating `access_token`s and `refresh_token`s.
 Authenticated calls require an `access_token` in request metadata to be included / directly as the value of the
 `authorization` header (no `Bearer ` prefix).

 First, use the [`CreateAccount`](#grpc-api-CreateAccount) or [`Login`](#grpc-api-Login) RPCs to fetch (and store) an initial
 `refresh_token` and `access_token`. Clients should use the `access_token` until it expires,
 then use the `refresh_token` to call the [`AccessToken`](#grpc-api-AccessToken) RPC for a new one. (The `AccessToken` RPC
 may, at random, also return a new `refresh_token`. If so, it should immediately replace the old
 one in client storage.)

 #### Federation
 Whereas other federated social networks (e.g. ActivityPub) have both client-server and server-server APIs,
 Jonline only has client-server APIs. While server-to-server communication is possible, nothing but some
 "nice to have" features require it, so it is not used.

 ##### Federated Servers
 Jonline servers can recommend other servers to clients with the `federation_info` field (a [`FederationInfo` message](http://localhost/docs/protocol#federationinfo)) in [`ServerConfiguration`](#jonline-ServerConfiguration).
 Clients can use this information to discover other servers, or users can add new servers manually.
 Note that, at least for web clients, this means everything is subject to CORS. In the future, Jonline will
 allow CORS to be configured in a "strict" mode, so someone else's Jonline server cannot be used to access your server's data
 unless you explicitly allow it.

 ##### Federated Profiles
 Jonline users can federate with users on any other Jonline server. This works by two-way verification:
 For example, Jon has the user [`jonline.io/jon`](https://jonline.io/jon), [`oakcity.social/jon`](https://oakcity.social/jon),
 and [`bullcity.social/jon`](https://bullcity.social/jon) associated with one another. 
 The UI will only show federated profiles if *both use profiles* have federated with one another.

 This mechanism also allows users to link multiple profiles on the same server together. For instance, [`bullcity.social/jon`](https://bullcity.social/jon)
 and [`bullcity.social/openmic`](https://bullcity.social/openmic) are linked together, but [`bullcity.social/openmic`](https://bullcity.social/openmic)
 isn't linked to [`jonline.io/jon`](https://jonline.io/jon) or [`oakcity.social/jon`](https://oakcity.social/jon).

 Federated profiles are managed via the `federated_profiles` field (a `repeated` [`FederatedAccount`](http://localhost/docs/protocol#jonline-FederatedAccount)) in the [`User`](#jonline-User) message.

 #### HTTP Endpoints

 ##### iCalendar/RFC5545 (`GET /calendar.ics`, `GET /calendar.ics?user_id={id}`)
 Jonline events support iCalendar/RFC5545. Only public events are included in the calendar.
 Users can "subscribe" to a Jonline server at, for instance, `https://jonline.io/calendar.ics` 
 to get a calendar of all public events on the server.
 Users can also subscribe to a user's calendar at, for instance, `https://jonline.io/calendar.ics?user_id=CruFm`
 to get a calendar of all public events for that user.
 In the Tamagui/React frontend, links to the ICS endpoints are provided in the Upcoming Events section of the home page,
 the Events page, and the user profile pages for all users with events in the last 3 months (or in the future).

 ##### Robots & Sitemap (`GET /robots.txt` and `GET /sitemap.xml`)
 Jonline servers are expected to serve a `robots.txt` file at `/robots.txt` and a `sitemap.xml` file at `/sitemap.xml`.

 ##### Favicons (`GET /favicon.ico`, `GET /favicon.png`)
 Favicons in a couple of formats.

 ##### Media (`GET /media/{id}` and `POST /media`)
 See the [Media](#jonline-Media) section for details on how to upload/download media files.

 ##### HTTP-based client host negotiation (for external CDNs) (`GET /backend_host`)
 When first negotiating the gRPC connection to a host, say, `jonline.io`, before attempting
 to connect to `jonline.io` via gRPC on 27707/443, the client
 is expected to first attempt to `GET jonline.io/backend_host` over HTTP (port 80) or HTTPS (port 443)
 (depending upon whether the gRPC server is expected to have TLS). If the `backend_host` string resource
 is a valid domain, say, `jonline.io.itsj.online`, the client is expected to connect
 to `jonline.io.itsj.online` on port 27707/443 instead. To users, the server should still *generally* appear to 
 be `jonline.io`. The client can trust `jonline.io/backend_host` to always point to the correct backend host for
 `jonline.io`.

 This negotiation enables support for external CDNs as frontends. See https://jonline.io/about?section=cdn for
 more information about external CDN setup. Developers may wish to review the [React/Tamagui](https://github.com/JonLatane/jonline/blob/main/frontends/tamagui/packages/app/store/clients.ts#L116) 
 and [Flutter](https://github.com/JonLatane/jonline/blob/main/frontends/flutter/lib/models/jonline_clients.dart#L26) 
 client implementations of this negotiation.

 In the works to be released soon, Jonline will also support a "fully behind CDN" mode, where gRPC is served over port 443 and HTTP over port
 80, with no HTTPS web page/media serving (other than the HTTPS that naturally underpins gRPC-Web). This is designed to use Cloudflare's gRPC
 proxy support. With this, both web and gRPC resources can live behind a CDN.

 ### gRPC API


@docs accessToken, configureServer, createAccount, createEvent, createEventSyncDestination, createEventSyncSource, createFollow, createGroup

@docs createGroupPost, createMembership, createPost, defederateProfile, deleteEvent, deleteEventAttendance, deleteEventSyncDestination

@docs deleteEventSyncSource, deleteFollow, deleteGroup, deleteGroupPost, deleteMedia, deleteMembership, deletePost, deleteUser

@docs federateProfile, getCurrentUser, getEventAttendances, getEventSyncDestinations, getEventSyncSources, getEvents, getGroupPosts

@docs getGroups, getMedia, getMembers, getMessages, getPosts, getServerConfiguration, getServiceVersion, getUsers, login, resetData, resetPassword

@docs sendMessage, starPost, syncEventInstance, unstarPost, updateEvent, updateEventSyncDestination, updateEventSyncSource, updateFollow

@docs updateGroup, updateGroupPost, updateMembership, updatePost, updateUser, upsertEventAttendance

-}

import Grpc.Internal
import Proto.Google.Protobuf
import Proto.Jonline


{-| A template for a gRPC call to the method 'ResetData' sending a `Empty` to get back a `Empty`.

 Delete ALL Media, Posts, Groups and Users except the user who performed the RPC. *Authenticated.*
 Requires `ADMIN` permissions.
 Note: Server Configuration is not deleted.


-}
resetData : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Google.Protobuf.Empty
resetData =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "ResetData"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'ConfigureServer' sending a `ServerConfiguration` to get back a `ServerConfiguration`.

 Configure the server (i.e. the response to GetServerConfiguration). *Authenticated.*
 Requires `ADMIN` permissions.


-}
configureServer : Grpc.Internal.Rpc Proto.Jonline.ServerConfiguration Proto.Jonline.ServerConfiguration
configureServer =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "ConfigureServer"
        , encoder = Proto.Jonline.encodeServerConfiguration
        , decoder = Proto.Jonline.decodeServerConfiguration
        }


{-| A template for a gRPC call to the method 'DefederateProfile' sending a `FederatedAccount` to get back a `Empty`.

 *Authenticated*.


-}
defederateProfile : Grpc.Internal.Rpc Proto.Jonline.FederatedAccount Proto.Google.Protobuf.Empty
defederateProfile =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DefederateProfile"
        , encoder = Proto.Jonline.encodeFederatedAccount
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'FederateProfile' sending a `FederatedAccount` to get back a `FederatedAccount`.

 Federate the current user's profile with another user profile. *Authenticated*.


-}
federateProfile : Grpc.Internal.Rpc Proto.Jonline.FederatedAccount Proto.Jonline.FederatedAccount
federateProfile =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "FederateProfile"
        , encoder = Proto.Jonline.encodeFederatedAccount
        , decoder = Proto.Jonline.decodeFederatedAccount
        }


{-| A template for a gRPC call to the method 'DeleteEventAttendance' sending a `EventAttendance` to get back a `Empty`.

 Delete an EventAttendance.  *Publicly accessible **or** Authenticated, with anonymous RSVP support.*


-}
deleteEventAttendance : Grpc.Internal.Rpc Proto.Jonline.EventAttendance Proto.Google.Protobuf.Empty
deleteEventAttendance =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteEventAttendance"
        , encoder = Proto.Jonline.encodeEventAttendance
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpsertEventAttendance' sending a `EventAttendance` to get back a `EventAttendance`.

 Upsert an EventAttendance. *Publicly accessible **or** Authenticated, with anonymous RSVP support.*
 See [EventAttendance](#jonline-EventAttendance) and [AnonymousAttendee](#jonline-AnonymousAttendee)
 for details. tl;dr: Anonymous RSVPs may updated/deleted with the `AnonymousAttendee.auth_token`
 returned by this RPC (the client should save this for the user, and ideally, offer a link
 with the token).


-}
upsertEventAttendance : Grpc.Internal.Rpc Proto.Jonline.EventAttendance Proto.Jonline.EventAttendance
upsertEventAttendance =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpsertEventAttendance"
        , encoder = Proto.Jonline.encodeEventAttendance
        , decoder = Proto.Jonline.decodeEventAttendance
        }


{-| A template for a gRPC call to the method 'GetEventAttendances' sending a `GetEventAttendancesRequest` to get back a `EventAttendances`.

 Gets EventAttendances for an EventInstance. *Publicly accessible **or** Authenticated.*


-}
getEventAttendances : Grpc.Internal.Rpc Proto.Jonline.GetEventAttendancesRequest Proto.Jonline.EventAttendances
getEventAttendances =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetEventAttendances"
        , encoder = Proto.Jonline.encodeGetEventAttendancesRequest
        , decoder = Proto.Jonline.decodeEventAttendances
        }


{-| A template for a gRPC call to the method 'SyncEventInstance' sending a `SyncEventInstanceRequest` to get back a `EventInstance`.

 Syncs (cross-posts) an EventInstance to an EventSyncDestination. *Authenticated* (destination owner, or Admin), requires `SYNC_EVENTS_TO_FACEBOOK` (or Admin).


-}
syncEventInstance : Grpc.Internal.Rpc Proto.Jonline.SyncEventInstanceRequest Proto.Jonline.EventInstance
syncEventInstance =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "SyncEventInstance"
        , encoder = Proto.Jonline.encodeSyncEventInstanceRequest
        , decoder = Proto.Jonline.decodeEventInstance
        }


{-| A template for a gRPC call to the method 'DeleteEventSyncDestination' sending a `DeleteEventSyncDestinationRequest` to get back a `Empty`.

 Deletes an EventSyncDestination. *Authenticated* (owner, or Admin).


-}
deleteEventSyncDestination :
    Grpc.Internal.Rpc Proto.Jonline.DeleteEventSyncDestinationRequest Proto.Google.Protobuf.Empty
deleteEventSyncDestination =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteEventSyncDestination"
        , encoder = Proto.Jonline.encodeDeleteEventSyncDestinationRequest
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateEventSyncDestination' sending a `EventSyncDestination` to get back a `EventSyncDestination`.

 Updates an EventSyncDestination. *Authenticated* (owner, or Admin for any user's), requires `SYNC_EVENTS_TO_FACEBOOK` (or Admin).


-}
updateEventSyncDestination : Grpc.Internal.Rpc Proto.Jonline.EventSyncDestination Proto.Jonline.EventSyncDestination
updateEventSyncDestination =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateEventSyncDestination"
        , encoder = Proto.Jonline.encodeEventSyncDestination
        , decoder = Proto.Jonline.decodeEventSyncDestination
        }


{-| A template for a gRPC call to the method 'CreateEventSyncDestination' sending a `EventSyncDestination` to get back a `EventSyncDestination`.

 Creates an EventSyncDestination for the current user. *Authenticated*, requires `SYNC_EVENTS_TO_FACEBOOK` (or Admin).


-}
createEventSyncDestination : Grpc.Internal.Rpc Proto.Jonline.EventSyncDestination Proto.Jonline.EventSyncDestination
createEventSyncDestination =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateEventSyncDestination"
        , encoder = Proto.Jonline.encodeEventSyncDestination
        , decoder = Proto.Jonline.decodeEventSyncDestination
        }


{-| A template for a gRPC call to the method 'GetEventSyncDestinations' sending a `User` to get back a `GetEventSyncDestinationsResponse`.

 Gets a user's EventSyncDestinations. *Authenticated* (self, or Admin for any user).


-}
getEventSyncDestinations : Grpc.Internal.Rpc Proto.Jonline.User Proto.Jonline.GetEventSyncDestinationsResponse
getEventSyncDestinations =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetEventSyncDestinations"
        , encoder = Proto.Jonline.encodeUser
        , decoder = Proto.Jonline.decodeGetEventSyncDestinationsResponse
        }


{-| A template for a gRPC call to the method 'DeleteEventSyncSource' sending a `DeleteEventSyncSourceRequest` to get back a `Empty`.

 Deletes an EventSyncSource. *Authenticated* (owner, or Admin).


-}
deleteEventSyncSource : Grpc.Internal.Rpc Proto.Jonline.DeleteEventSyncSourceRequest Proto.Google.Protobuf.Empty
deleteEventSyncSource =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteEventSyncSource"
        , encoder = Proto.Jonline.encodeDeleteEventSyncSourceRequest
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateEventSyncSource' sending a `EventSyncSource` to get back a `EventSyncSource`.

 Updates an EventSyncSource. *Authenticated* (owner, or Admin for any user's), requires `SYNCHRONIZE_EVENTS` (or Admin).


-}
updateEventSyncSource : Grpc.Internal.Rpc Proto.Jonline.EventSyncSource Proto.Jonline.EventSyncSource
updateEventSyncSource =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateEventSyncSource"
        , encoder = Proto.Jonline.encodeEventSyncSource
        , decoder = Proto.Jonline.decodeEventSyncSource
        }


{-| A template for a gRPC call to the method 'CreateEventSyncSource' sending a `EventSyncSource` to get back a `EventSyncSource`.

 Creates an EventSyncSource for the current user. *Authenticated*, requires `SYNCHRONIZE_EVENTS` (or Admin).


-}
createEventSyncSource : Grpc.Internal.Rpc Proto.Jonline.EventSyncSource Proto.Jonline.EventSyncSource
createEventSyncSource =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateEventSyncSource"
        , encoder = Proto.Jonline.encodeEventSyncSource
        , decoder = Proto.Jonline.decodeEventSyncSource
        }


{-| A template for a gRPC call to the method 'GetEventSyncSources' sending a `User` to get back a `GetEventSyncSourcesResponse`.

 Gets a user's EventSyncSources. *Authenticated* (self, or Admin for any user).


-}
getEventSyncSources : Grpc.Internal.Rpc Proto.Jonline.User Proto.Jonline.GetEventSyncSourcesResponse
getEventSyncSources =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetEventSyncSources"
        , encoder = Proto.Jonline.encodeUser
        , decoder = Proto.Jonline.decodeGetEventSyncSourcesResponse
        }


{-| A template for a gRPC call to the method 'DeleteEvent' sending a `Event` to get back a `Event`.

 (TODO) (Soft) deletes a Event. Returns the deleted version of the Event. *Authenticated.*


-}
deleteEvent : Grpc.Internal.Rpc Proto.Jonline.Event Proto.Jonline.Event
deleteEvent =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteEvent"
        , encoder = Proto.Jonline.encodeEvent
        , decoder = Proto.Jonline.decodeEvent
        }


{-| A template for a gRPC call to the method 'UpdateEvent' sending a `Event` to get back a `Event`.

 Updates an Event. *Authenticated.*


-}
updateEvent : Grpc.Internal.Rpc Proto.Jonline.Event Proto.Jonline.Event
updateEvent =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateEvent"
        , encoder = Proto.Jonline.encodeEvent
        , decoder = Proto.Jonline.decodeEvent
        }


{-| A template for a gRPC call to the method 'CreateEvent' sending a `Event` to get back a `Event`.

 Creates an Event. *Authenticated.*


-}
createEvent : Grpc.Internal.Rpc Proto.Jonline.Event Proto.Jonline.Event
createEvent =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateEvent"
        , encoder = Proto.Jonline.encodeEvent
        , decoder = Proto.Jonline.decodeEvent
        }


{-| A template for a gRPC call to the method 'GetEvents' sending a `GetEventsRequest` to get back a `GetEventsResponse`.

 Gets Events. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Events of `GLOBAL_PUBLIC` visibility.


-}
getEvents : Grpc.Internal.Rpc Proto.Jonline.GetEventsRequest Proto.Jonline.GetEventsResponse
getEvents =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetEvents"
        , encoder = Proto.Jonline.encodeGetEventsRequest
        , decoder = Proto.Jonline.decodeGetEventsResponse
        }


{-| A template for a gRPC call to the method 'DeleteGroupPost' sending a `GroupPost` to get back a `Empty`.

 Delete a GroupPost. *Authenticated.*


-}
deleteGroupPost : Grpc.Internal.Rpc Proto.Jonline.GroupPost Proto.Google.Protobuf.Empty
deleteGroupPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteGroupPost"
        , encoder = Proto.Jonline.encodeGroupPost
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateGroupPost' sending a `GroupPost` to get back a `GroupPost`.

 Group Moderators: Approve/Reject a GroupPost. *Authenticated.*


-}
updateGroupPost : Grpc.Internal.Rpc Proto.Jonline.GroupPost Proto.Jonline.GroupPost
updateGroupPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateGroupPost"
        , encoder = Proto.Jonline.encodeGroupPost
        , decoder = Proto.Jonline.decodeGroupPost
        }


{-| A template for a gRPC call to the method 'CreateGroupPost' sending a `GroupPost` to get back a `GroupPost`.

 Cross-post a Post to a Group. *Authenticated.*


-}
createGroupPost : Grpc.Internal.Rpc Proto.Jonline.GroupPost Proto.Jonline.GroupPost
createGroupPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateGroupPost"
        , encoder = Proto.Jonline.encodeGroupPost
        , decoder = Proto.Jonline.decodeGroupPost
        }


{-| A template for a gRPC call to the method 'GetGroupPosts' sending a `GetGroupPostsRequest` to get back a `GetGroupPostsResponse`.

 Get GroupPosts for a Post (and optional group). *Publicly accessible **or** Authenticated.*


-}
getGroupPosts : Grpc.Internal.Rpc Proto.Jonline.GetGroupPostsRequest Proto.Jonline.GetGroupPostsResponse
getGroupPosts =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetGroupPosts"
        , encoder = Proto.Jonline.encodeGetGroupPostsRequest
        , decoder = Proto.Jonline.decodeGetGroupPostsResponse
        }


{-| A template for a gRPC call to the method 'UnstarPost' sending a `Post` to get back a `Post`.

 Unstar a Post. *Unauthenticated.*


-}
unstarPost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
unstarPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UnstarPost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'StarPost' sending a `Post` to get back a `Post`.

 Star a Post. *Unauthenticated.*


-}
starPost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
starPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "StarPost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'DeletePost' sending a `Post` to get back a `Post`.

 (TODO) (Soft) deletes a Post. Returns the deleted version of the Post. *Authenticated.*


-}
deletePost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
deletePost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeletePost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'UpdatePost' sending a `Post` to get back a `Post`.

 Updates a Post. *Authenticated.*


-}
updatePost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
updatePost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdatePost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'CreatePost' sending a `Post` to get back a `Post`.

 Creates a Post. *Authenticated.*


-}
createPost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
createPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreatePost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'GetPosts' sending a `GetPostsRequest` to get back a `GetPostsResponse`.

 Gets Posts. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Posts of `GLOBAL_PUBLIC` visibility.


-}
getPosts : Grpc.Internal.Rpc Proto.Jonline.GetPostsRequest Proto.Jonline.GetPostsResponse
getPosts =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetPosts"
        , encoder = Proto.Jonline.encodeGetPostsRequest
        , decoder = Proto.Jonline.decodeGetPostsResponse
        }


{-| A template for a gRPC call to the method 'DeleteMembership' sending a `Membership` to get back a `Empty`.

 Leave a group (or cancel membership request). *Authenticated.*


-}
deleteMembership : Grpc.Internal.Rpc Proto.Jonline.Membership Proto.Google.Protobuf.Empty
deleteMembership =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteMembership"
        , encoder = Proto.Jonline.encodeMembership
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateMembership' sending a `Membership` to get back a `Membership`.

 Update aspects of a user's membership. *Authenticated.*
 Updating permissions requires `ADMIN` permissions within the group, or `ADMIN` permissions for the user.
 Updating moderation (approving/denying/banning) requires the same, or `MODERATE_USERS` permissions within the group.


-}
updateMembership : Grpc.Internal.Rpc Proto.Jonline.Membership Proto.Jonline.Membership
updateMembership =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateMembership"
        , encoder = Proto.Jonline.encodeMembership
        , decoder = Proto.Jonline.decodeMembership
        }


{-| A template for a gRPC call to the method 'CreateMembership' sending a `Membership` to get back a `Membership`.

 Requests to join a group (or joins it), or sends an invite to the user. *Authenticated.*
 Memberships and moderations are set to their defaults.


-}
createMembership : Grpc.Internal.Rpc Proto.Jonline.Membership Proto.Jonline.Membership
createMembership =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateMembership"
        , encoder = Proto.Jonline.encodeMembership
        , decoder = Proto.Jonline.decodeMembership
        }


{-| A template for a gRPC call to the method 'GetMembers' sending a `GetMembersRequest` to get back a `GetMembersResponse`.

 Get Members (User+Membership) of a Group. *Publicly accessible **or** Authenticated.*


-}
getMembers : Grpc.Internal.Rpc Proto.Jonline.GetMembersRequest Proto.Jonline.GetMembersResponse
getMembers =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetMembers"
        , encoder = Proto.Jonline.encodeGetMembersRequest
        , decoder = Proto.Jonline.decodeGetMembersResponse
        }


{-| A template for a gRPC call to the method 'DeleteGroup' sending a `Group` to get back a `Empty`.

 Delete a Group. *Authenticated.*
 Requires `ADMIN` permissions within the group, or `ADMIN` permissions for the user.


-}
deleteGroup : Grpc.Internal.Rpc Proto.Jonline.Group Proto.Google.Protobuf.Empty
deleteGroup =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteGroup"
        , encoder = Proto.Jonline.encodeGroup
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateGroup' sending a `Group` to get back a `Group`.

 Update a Groups's information, default membership permissions or moderation. *Authenticated.*
 Requires `ADMIN` permissions within the group, or `ADMIN` permissions for the user.


-}
updateGroup : Grpc.Internal.Rpc Proto.Jonline.Group Proto.Jonline.Group
updateGroup =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateGroup"
        , encoder = Proto.Jonline.encodeGroup
        , decoder = Proto.Jonline.decodeGroup
        }


{-| A template for a gRPC call to the method 'CreateGroup' sending a `Group` to get back a `Group`.

 Creates a group with the current user as its admin. *Authenticated.*
 Requires the `CREATE_GROUPS` permission.


-}
createGroup : Grpc.Internal.Rpc Proto.Jonline.Group Proto.Jonline.Group
createGroup =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateGroup"
        , encoder = Proto.Jonline.encodeGroup
        , decoder = Proto.Jonline.decodeGroup
        }


{-| A template for a gRPC call to the method 'GetGroups' sending a `GetGroupsRequest` to get back a `GetGroupsResponse`.

 Gets Groups. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Groups of `GLOBAL_PUBLIC` visibility.


-}
getGroups : Grpc.Internal.Rpc Proto.Jonline.GetGroupsRequest Proto.Jonline.GetGroupsResponse
getGroups =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetGroups"
        , encoder = Proto.Jonline.encodeGetGroupsRequest
        , decoder = Proto.Jonline.decodeGetGroupsResponse
        }


{-| A template for a gRPC call to the method 'DeleteFollow' sending a `Follow` to get back a `Empty`.

 Unfollow (or unrequest) a user. *Authenticated.*


-}
deleteFollow : Grpc.Internal.Rpc Proto.Jonline.Follow Proto.Google.Protobuf.Empty
deleteFollow =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteFollow"
        , encoder = Proto.Jonline.encodeFollow
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateFollow' sending a `Follow` to get back a `Follow`.

 Used to approve follow requests. *Authenticated.*


-}
updateFollow : Grpc.Internal.Rpc Proto.Jonline.Follow Proto.Jonline.Follow
updateFollow =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateFollow"
        , encoder = Proto.Jonline.encodeFollow
        , decoder = Proto.Jonline.decodeFollow
        }


{-| A template for a gRPC call to the method 'CreateFollow' sending a `Follow` to get back a `Follow`.

 Follow (or request to follow) a user. *Authenticated.*


-}
createFollow : Grpc.Internal.Rpc Proto.Jonline.Follow Proto.Jonline.Follow
createFollow =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateFollow"
        , encoder = Proto.Jonline.encodeFollow
        , decoder = Proto.Jonline.decodeFollow
        }


{-| A template for a gRPC call to the method 'GetMessages' sending a `GetMessagesRequest` to get back a `GetMessagesResponse`.

 Gets Messages. *Authenticated.*
 `PERSONAL_MESSAGES(_TEXT_SEARCH)` (and looking up a single Message/MessagingGroup) requires the
 `READ_PERSONAL_MESSAGES` permission and only returns Messages the current user sent or received.
 `ALL_SYSTEM_MESSAGES(_TEXT_SEARCH)` requires the `READ_ALL_SYSTEM_MESSAGES` permission and returns
 every Message on the server.


-}
getMessages : Grpc.Internal.Rpc Proto.Jonline.GetMessagesRequest Proto.Jonline.GetMessagesResponse
getMessages =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetMessages"
        , encoder = Proto.Jonline.encodeGetMessagesRequest
        , decoder = Proto.Jonline.decodeGetMessagesResponse
        }


{-| A template for a gRPC call to the method 'SendMessage' sending a `SendMessageRequest` to get back a `Message`.

 Sends a Message to one or more recipients (creating/reusing their MessagingGroup). *Publicly
 accessible **or** Authenticated.* Like `CreatePost`/`CreateEvent`, authentication (if any) is via
 a standard `access_token`; unauthenticated calls are simply sent with no `sender`.


-}
sendMessage : Grpc.Internal.Rpc Proto.Jonline.SendMessageRequest Proto.Jonline.Message
sendMessage =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "SendMessage"
        , encoder = Proto.Jonline.encodeSendMessageRequest
        , decoder = Proto.Jonline.decodeMessage
        }


{-| A template for a gRPC call to the method 'DeleteUser' sending a `User` to get back a `Empty`.

 Deletes a user by ID. *Authenticated.*
 Deleting other users requires `ADMIN` permissions.


-}
deleteUser : Grpc.Internal.Rpc Proto.Jonline.User Proto.Google.Protobuf.Empty
deleteUser =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteUser"
        , encoder = Proto.Jonline.encodeUser
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateUser' sending a `User` to get back a `User`.

 Update a user by ID. *Authenticated.*
 Updating other users requires `ADMIN` permissions.


-}
updateUser : Grpc.Internal.Rpc Proto.Jonline.User Proto.Jonline.User
updateUser =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateUser"
        , encoder = Proto.Jonline.encodeUser
        , decoder = Proto.Jonline.decodeUser
        }


{-| A template for a gRPC call to the method 'GetUsers' sending a `GetUsersRequest` to get back a `GetUsersResponse`.

 Gets Users. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Users of `GLOBAL_PUBLIC` visibility.


-}
getUsers : Grpc.Internal.Rpc Proto.Jonline.GetUsersRequest Proto.Jonline.GetUsersResponse
getUsers =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetUsers"
        , encoder = Proto.Jonline.encodeGetUsersRequest
        , decoder = Proto.Jonline.decodeGetUsersResponse
        }


{-| A template for a gRPC call to the method 'DeleteMedia' sending a `Media` to get back a `Empty`.

 Deletes a media item by ID. *Authenticated.* Note that media may still be accessible for 12 hours after deletes are requested, as separate jobs clean it up from S3/MinIO.
 Deleting other users' media requires `ADMIN` permissions.


-}
deleteMedia : Grpc.Internal.Rpc Proto.Jonline.Media Proto.Google.Protobuf.Empty
deleteMedia =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteMedia"
        , encoder = Proto.Jonline.encodeMedia
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'GetMedia' sending a `GetMediaRequest` to get back a `GetMediaResponse`.

 Gets Media (Images, Videos, etc) uploaded/owned by the current user. *Authenticated.* To upload/download actual Media blob/binary data, use the [HTTP Media APIs](#media).


-}
getMedia : Grpc.Internal.Rpc Proto.Jonline.GetMediaRequest Proto.Jonline.GetMediaResponse
getMedia =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetMedia"
        , encoder = Proto.Jonline.encodeGetMediaRequest
        , decoder = Proto.Jonline.decodeGetMediaResponse
        }


{-| A template for a gRPC call to the method 'ResetPassword' sending a `ResetPasswordRequest` to get back a `Empty`.

 Resets the current user's - or, for admins, a given user's - password. *Authenticated.*


-}
resetPassword : Grpc.Internal.Rpc Proto.Jonline.ResetPasswordRequest Proto.Google.Protobuf.Empty
resetPassword =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "ResetPassword"
        , encoder = Proto.Jonline.encodeResetPasswordRequest
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'GetCurrentUser' sending a `Empty` to get back a `User`.

 Gets the current user. *Authenticated.*


-}
getCurrentUser : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Jonline.User
getCurrentUser =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetCurrentUser"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Jonline.decodeUser
        }


{-| A template for a gRPC call to the method 'AccessToken' sending a `AccessTokenRequest` to get back a `AccessTokenResponse`.

 Gets a new `access_token` (and possibly a new `refresh_token`, which should replace the old one in client storage), given a `refresh_token`. *Publicly accessible.*


-}
accessToken : Grpc.Internal.Rpc Proto.Jonline.AccessTokenRequest Proto.Jonline.AccessTokenResponse
accessToken =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "AccessToken"
        , encoder = Proto.Jonline.encodeAccessTokenRequest
        , decoder = Proto.Jonline.decodeAccessTokenResponse
        }


{-| A template for a gRPC call to the method 'Login' sending a `LoginRequest` to get back a `RefreshTokenResponse`.

 Logs in a user and provides a `refresh_token` (along with an `access_token`). *Publicly accessible.*


-}
login : Grpc.Internal.Rpc Proto.Jonline.LoginRequest Proto.Jonline.RefreshTokenResponse
login =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "Login"
        , encoder = Proto.Jonline.encodeLoginRequest
        , decoder = Proto.Jonline.decodeRefreshTokenResponse
        }


{-| A template for a gRPC call to the method 'CreateAccount' sending a `CreateAccountRequest` to get back a `RefreshTokenResponse`.

 Creates a user account and provides a `refresh_token` (along with an `access_token`). *Publicly accessible.*


-}
createAccount : Grpc.Internal.Rpc Proto.Jonline.CreateAccountRequest Proto.Jonline.RefreshTokenResponse
createAccount =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateAccount"
        , encoder = Proto.Jonline.encodeCreateAccountRequest
        , decoder = Proto.Jonline.decodeRefreshTokenResponse
        }


{-| A template for a gRPC call to the method 'GetServerConfiguration' sending a `Empty` to get back a `ServerConfiguration`.

 Gets the Jonline server's configuration. *Publicly accessible.*


-}
getServerConfiguration : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Jonline.ServerConfiguration
getServerConfiguration =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetServerConfiguration"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Jonline.decodeServerConfiguration
        }


{-| A template for a gRPC call to the method 'GetServiceVersion' sending a `Empty` to get back a `GetServiceVersionResponse`.

 Get the version (from Cargo) of the Jonline service. *Publicly accessible.*


-}
getServiceVersion : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Jonline.GetServiceVersionResponse
getServiceVersion =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetServiceVersion"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Jonline.decodeGetServiceVersionResponse
        }
