{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.Jonline exposing (accessToken, configureServer, createAccount, createEvent, createFollow, createGroup, createGroupPost, createMembership, createPost, defederateProfile, deleteEvent, deleteEventAttendance, deleteFollow, deleteGroup, deleteGroupPost, deleteMedia, deleteMembership, deletePost, deleteUser, federateProfile, getCurrentUser, getEventAttendances, getEvents, getGroupPosts, getGroups, getMedia, getMembers, getPosts, getServerConfiguration, getServiceVersion, getUsers, login, resetData, resetPassword, starPost, unstarPost, updateEvent, updateFollow, updateGroup, updateGroupPost, updateMembership, updatePost, updateUser, upsertEventAttendance)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `jonline.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

 A Jonline server is generally expected to run a gRPC server on port 27707 and/or 443, and an HTTP server on port 80 and/or 443.
 The bulk of these docs involve the [gRPC API](#grpc-api) (the "protocol"), while the HTTP server is expected to serve up web apps (React and, previously, Flutter),
 [media files](#jonline-Media), and a [`backend_host` resource for client/host negotiation](#http-based-client-host-negotiation-for-external-cdns).
 Jonline serves up a few other [HTTP endpoints](#http-endpoints), providing a `/sitemap.xml`, `/robots.txt`, iCal/RFC5545 subscription endpoints, and more,
 but these are essentially accessories to the core APIs.

 #### Authentication
 Jonline uses a standard OAuth2 flow (over gRPC) for authentication, with rotating `access_token`s and `refresh_token`s.
 Authenticated calls require an `access_token` in request metadata to be included / directly as the value of the
 `authorization` header (no `Bearer ` prefix).

 First, use the `CreateAccount` or `Login` RPCs to fetch (and store) an initial
 `refresh_token` and `access_token`. Clients should use the `access_token` until it expires,
 then use the `refresh_token` to call the `AccessToken` RPC for a new one. (The `AccessToken` RPC
 may, at random, also return a new `refresh_token`. If so, it should immediately replace the old
 one in client storage.)

 #### Dumfederation
 Whereas other federated social networks (e.g. ActivityPub) have both client-server and server-server APIs,
 Jonline only has client-server APIs. While server-to-server communication is possible, nothing but some
 "nice to have" features require it, so it is not used.

 ##### Federated Servers
 Jonline servers can recommend other servers to clients with the `federation_info` field (a [`FederationInfo` message](http://localhost/docs/protocol#federationinfo)) in [`ServerConfiguration`](#jonline-ServerConfiguration).
 Clients can use this information to discover other servers, or users can add new servers manually.
 Note that, at least for web clients, this means everything is subject to CORS. In the future, Jonline will
 allow CORS to be configured in a "strict" mode, so someone else's Jonline server cannot be used to access your server's data
 unless you explicitly allow it.

 #### Federated Profiles
 Jonline users can federate with users on any other Jonline server. This works by two-way verification:
 For example, Jon has the user [`jonline.io/jon`](https://jonline.io/jon), [`oakcity.social/jon`](https://oakcity.social/jon),
 and [`bullcity.social/jon`](https://bullcity.social/jon) associated with one another. 
 The UI will only show federated profiles if *both use profiles* have federated with one another.

 This mechanism also allows users to link multiple profiles on the same server together. For instance, [`bullcity.social/jon`](https://bullcity.social/jon)
 and [`bullcity.social/openmic`](https://bullcity.social/openmic) are linked together, but [`bullcity.social/openmic`](https://bullcity.social/openmic)
 isn't linked to [`jonline.io/jon`](https://jonline.io/jon) or [`oakcity.social/jon`](https://oakcity.social/jon).

 Federated profiles are managed via the `federated_profiles` field (a `repeated` [`FederatedAccount`](http://localhost/docs/protocol#jonline-FederatedAccount)) in the [`User`](#jonline-User) message.

 #### HTTP Endpoints

 ##### iCalendar/RFC5545 (`GET /calendar.ics`, `GET /calendar.ics?user_id={id}`)
 Jonline events support iCalendar/RFC5545. Only public events are included in the calendar.
 Users can "subscribe" to a Jonline server at, for instance, `https://jonline.io/calendar.ics` 
 to get a calendar of all public events on the server.
 Users can also subscribe to a user's calendar at, for instance, `https://jonline.io/calendar.ics?user_id=CruFm`
 to get a calendar of all public events for that user.
 In the Tamagui/React frontend, links to the ICS endpoints are provided in the Upcoming Events section of the home page,
 the Events page, and the user profile pages for all users with events in the last 3 months (or in the future).

 ##### Robots & Sitemap (`GET /robots.txt` and `GET /sitemap.xml`)
 Jonline servers are expected to serve a `robots.txt` file at `/robots.txt` and a `sitemap.xml` file at `/sitemap.xml`.

 ##### Media (`GET /media/{id}` and `POST /media`)
 See the [Media](#jonline-Media) section for details on how to upload/download media files.

 ##### HTTP-based client host negotiation (for external CDNs) (`GET /backend_host`)
 When first negotiating the gRPC connection to a host, say, `jonline.io`, before attempting
 to connect to `jonline.io` via gRPC on 27707/443, the client
 is expected to first attempt to `GET jonline.io/backend_host` over HTTP (port 80) or HTTPS (port 443)
 (depending upon whether the gRPC server is expected to have TLS). If the `backend_host` string resource
 is a valid domain, say, `jonline.io.itsj.online`, the client is expected to connect
 to `jonline.io.itsj.online` on port 27707/443 instead. To users, the server should still *generally* appear to 
 be `jonline.io`. The client can trust `jonline.io/backend_host` to always point to the correct backend host for
 `jonline.io`.

 This negotiation enables support for external CDNs as frontends. See https://jonline.io/about?section=cdn for
 more information about external CDN setup. Developers may wish to review the [React/Tamagui](https://github.com/JonLatane/jonline/blob/main/frontends/tamagui/packages/app/store/clients.ts#L116) 
 and [Flutter](https://github.com/JonLatane/jonline/blob/main/frontends/flutter/lib/models/jonline_clients.dart#L26) 
 client implementations of this negotiation.

 In the works to be released soon, Jonline will also support a "fully behind CDN" mode, where gRPC is served over port 443 and HTTP over port
 80, with no HTTPS web page/media serving (other than the HTTPS that naturally underpins gRPC-Web). This is designed to use Cloudflare's gRPC
 proxy support. With this, both web and gRPC resources can live behind a CDN.

 #### API Design Notes
 ##### Moderation and Visibility
 Jonline APIs are designed to support `Moderation` and `Visibility` controls at the level of individual entities. However, to keep things
 DRY, moderation and visibility controls are only implemented for `User`s, `Media`, `Group`s, and `Post`s.

 `Event`s and future `Post`-like types simply use the same implementation as their contained `Post`s. The intent here is to maximize
 both shared code and implementation robustness.

 ##### Composition Over Inheritance
 Jonline's APIs are designed using composition over inheritance. For instance, an `Event` contains
 a `Post` rather than extending it. This pattern fits well all the way from the data model (very boring, safe, and normalized), 
 through Rust code implementing APIs, to both functional React code and more-OOP Flutter code equally well.

 ##### Predictable Atomicity
 The use of composition over inheritance also means that Jonline APIs can be *predictably* non-atomic based on their compositional structure.
 For instance, `UpdatePost` is fully atomic.

 `UpdateEvent`, however, is non-atomic. Given that an `Event` has a `Post` and many `EventInstance`s, 
 `UpdateEvent` will first update the `Post` atomically (literally calling the `UpdatePost` RPC),
 then the `Event` atomically, and then finally process updates to its `EventInstance`s in a final atomic operation. 

 Because moderation/visibility lives at the `Post` level, this means that a developer error in `UpdateEvents` cannot prevent 
 visibility and moderation changes from being made in Events, even if there are errors elsewhere.
 This should prove a robust pattern for any future entities intended to be shareable at a Group level with visibility and
 moderation controls (for instance, `Sheet`, `SharedExpenseReport`, `SharedCalendar`, etc.). The entire architecture should promote this
 approach to predictable atomicity.

 ### gRPC API


@docs accessToken, configureServer, createAccount, createEvent, createFollow, createGroup, createGroupPost, createMembership, createPost

@docs defederateProfile, deleteEvent, deleteEventAttendance, deleteFollow, deleteGroup, deleteGroupPost, deleteMedia, deleteMembership

@docs deletePost, deleteUser, federateProfile, getCurrentUser, getEventAttendances, getEvents, getGroupPosts, getGroups, getMedia, getMembers

@docs getPosts, getServerConfiguration, getServiceVersion, getUsers, login, resetData, resetPassword, starPost, unstarPost, updateEvent

@docs updateFollow, updateGroup, updateGroupPost, updateMembership, updatePost, updateUser, upsertEventAttendance

-}

import Grpc.Internal
import Proto.Google.Protobuf
import Proto.Jonline


{-| A template for a gRPC call to the method 'ResetData' sending a `Empty` to get back a `Empty`.

 Delete ALL Media, Posts, Groups and Users except the user who performed the RPC. *Authenticated.*
 Requires `ADMIN` permissions.
 Note: Server Configuration is not deleted.


-}
resetData : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Google.Protobuf.Empty
resetData =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "ResetData"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'ConfigureServer' sending a `ServerConfiguration` to get back a `ServerConfiguration`.

 Configure the server (i.e. the response to GetServerConfiguration). *Authenticated.*
 Requires `ADMIN` permissions.


-}
configureServer : Grpc.Internal.Rpc Proto.Jonline.ServerConfiguration Proto.Jonline.ServerConfiguration
configureServer =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "ConfigureServer"
        , encoder = Proto.Jonline.encodeServerConfiguration
        , decoder = Proto.Jonline.decodeServerConfiguration
        }


{-| A template for a gRPC call to the method 'DefederateProfile' sending a `FederatedAccount` to get back a `Empty`.

 *Authenticated*.


-}
defederateProfile : Grpc.Internal.Rpc Proto.Jonline.FederatedAccount Proto.Google.Protobuf.Empty
defederateProfile =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DefederateProfile"
        , encoder = Proto.Jonline.encodeFederatedAccount
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'FederateProfile' sending a `FederatedAccount` to get back a `FederatedAccount`.

 Federate the current user's profile with another user profile. *Authenticated*.


-}
federateProfile : Grpc.Internal.Rpc Proto.Jonline.FederatedAccount Proto.Jonline.FederatedAccount
federateProfile =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "FederateProfile"
        , encoder = Proto.Jonline.encodeFederatedAccount
        , decoder = Proto.Jonline.decodeFederatedAccount
        }


{-| A template for a gRPC call to the method 'DeleteEventAttendance' sending a `EventAttendance` to get back a `Empty`.

 Delete an EventAttendance.  *Publicly accessible **or** Authenticated, with anonymous RSVP support.*


-}
deleteEventAttendance : Grpc.Internal.Rpc Proto.Jonline.EventAttendance Proto.Google.Protobuf.Empty
deleteEventAttendance =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteEventAttendance"
        , encoder = Proto.Jonline.encodeEventAttendance
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpsertEventAttendance' sending a `EventAttendance` to get back a `EventAttendance`.

 Upsert an EventAttendance. *Publicly accessible **or** Authenticated, with anonymous RSVP support.*
 See [EventAttendance](#jonline-EventAttendance) and [AnonymousAttendee](#jonline-AnonymousAttendee)
 for details. tl;dr: Anonymous RSVPs may updated/deleted with the `AnonymousAttendee.auth_token`
 returned by this RPC (the client should save this for the user, and ideally, offer a link
 with the token).


-}
upsertEventAttendance : Grpc.Internal.Rpc Proto.Jonline.EventAttendance Proto.Jonline.EventAttendance
upsertEventAttendance =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpsertEventAttendance"
        , encoder = Proto.Jonline.encodeEventAttendance
        , decoder = Proto.Jonline.decodeEventAttendance
        }


{-| A template for a gRPC call to the method 'GetEventAttendances' sending a `GetEventAttendancesRequest` to get back a `EventAttendances`.

 Gets EventAttendances for an EventInstance. *Publicly accessible **or** Authenticated.*


-}
getEventAttendances : Grpc.Internal.Rpc Proto.Jonline.GetEventAttendancesRequest Proto.Jonline.EventAttendances
getEventAttendances =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetEventAttendances"
        , encoder = Proto.Jonline.encodeGetEventAttendancesRequest
        , decoder = Proto.Jonline.decodeEventAttendances
        }


{-| A template for a gRPC call to the method 'DeleteEvent' sending a `Event` to get back a `Event`.

 (TODO) (Soft) deletes a Event. Returns the deleted version of the Event. *Authenticated.*


-}
deleteEvent : Grpc.Internal.Rpc Proto.Jonline.Event Proto.Jonline.Event
deleteEvent =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteEvent"
        , encoder = Proto.Jonline.encodeEvent
        , decoder = Proto.Jonline.decodeEvent
        }


{-| A template for a gRPC call to the method 'UpdateEvent' sending a `Event` to get back a `Event`.

 Updates an Event. *Authenticated.*


-}
updateEvent : Grpc.Internal.Rpc Proto.Jonline.Event Proto.Jonline.Event
updateEvent =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateEvent"
        , encoder = Proto.Jonline.encodeEvent
        , decoder = Proto.Jonline.decodeEvent
        }


{-| A template for a gRPC call to the method 'CreateEvent' sending a `Event` to get back a `Event`.

 Creates an Event. *Authenticated.*


-}
createEvent : Grpc.Internal.Rpc Proto.Jonline.Event Proto.Jonline.Event
createEvent =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateEvent"
        , encoder = Proto.Jonline.encodeEvent
        , decoder = Proto.Jonline.decodeEvent
        }


{-| A template for a gRPC call to the method 'GetEvents' sending a `GetEventsRequest` to get back a `GetEventsResponse`.

 Gets Events. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Events of `GLOBAL_PUBLIC` visibility.


-}
getEvents : Grpc.Internal.Rpc Proto.Jonline.GetEventsRequest Proto.Jonline.GetEventsResponse
getEvents =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetEvents"
        , encoder = Proto.Jonline.encodeGetEventsRequest
        , decoder = Proto.Jonline.decodeGetEventsResponse
        }


{-| A template for a gRPC call to the method 'DeleteGroupPost' sending a `GroupPost` to get back a `Empty`.

 Delete a GroupPost. *Authenticated.*


-}
deleteGroupPost : Grpc.Internal.Rpc Proto.Jonline.GroupPost Proto.Google.Protobuf.Empty
deleteGroupPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteGroupPost"
        , encoder = Proto.Jonline.encodeGroupPost
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateGroupPost' sending a `GroupPost` to get back a `GroupPost`.

 Group Moderators: Approve/Reject a GroupPost. *Authenticated.*


-}
updateGroupPost : Grpc.Internal.Rpc Proto.Jonline.GroupPost Proto.Jonline.GroupPost
updateGroupPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateGroupPost"
        , encoder = Proto.Jonline.encodeGroupPost
        , decoder = Proto.Jonline.decodeGroupPost
        }


{-| A template for a gRPC call to the method 'CreateGroupPost' sending a `GroupPost` to get back a `GroupPost`.

 Cross-post a Post to a Group. *Authenticated.*


-}
createGroupPost : Grpc.Internal.Rpc Proto.Jonline.GroupPost Proto.Jonline.GroupPost
createGroupPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateGroupPost"
        , encoder = Proto.Jonline.encodeGroupPost
        , decoder = Proto.Jonline.decodeGroupPost
        }


{-| A template for a gRPC call to the method 'GetGroupPosts' sending a `GetGroupPostsRequest` to get back a `GetGroupPostsResponse`.

 Get GroupPosts for a Post (and optional group). *Publicly accessible **or** Authenticated.*


-}
getGroupPosts : Grpc.Internal.Rpc Proto.Jonline.GetGroupPostsRequest Proto.Jonline.GetGroupPostsResponse
getGroupPosts =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetGroupPosts"
        , encoder = Proto.Jonline.encodeGetGroupPostsRequest
        , decoder = Proto.Jonline.decodeGetGroupPostsResponse
        }


{-| A template for a gRPC call to the method 'UnstarPost' sending a `Post` to get back a `Post`.

 Unstar a Post. *Unauthenticated.*


-}
unstarPost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
unstarPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UnstarPost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'StarPost' sending a `Post` to get back a `Post`.

 Star a Post. *Unauthenticated.*


-}
starPost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
starPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "StarPost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'DeletePost' sending a `Post` to get back a `Post`.

 (TODO) (Soft) deletes a Post. Returns the deleted version of the Post. *Authenticated.*


-}
deletePost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
deletePost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeletePost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'UpdatePost' sending a `Post` to get back a `Post`.

 Updates a Post. *Authenticated.*


-}
updatePost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
updatePost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdatePost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'CreatePost' sending a `Post` to get back a `Post`.

 Creates a Post. *Authenticated.*


-}
createPost : Grpc.Internal.Rpc Proto.Jonline.Post Proto.Jonline.Post
createPost =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreatePost"
        , encoder = Proto.Jonline.encodePost
        , decoder = Proto.Jonline.decodePost
        }


{-| A template for a gRPC call to the method 'GetPosts' sending a `GetPostsRequest` to get back a `GetPostsResponse`.

 Gets Posts. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Posts of `GLOBAL_PUBLIC` visibility.


-}
getPosts : Grpc.Internal.Rpc Proto.Jonline.GetPostsRequest Proto.Jonline.GetPostsResponse
getPosts =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetPosts"
        , encoder = Proto.Jonline.encodeGetPostsRequest
        , decoder = Proto.Jonline.decodeGetPostsResponse
        }


{-| A template for a gRPC call to the method 'DeleteMembership' sending a `Membership` to get back a `Empty`.

 Leave a group (or cancel membership request). *Authenticated.*


-}
deleteMembership : Grpc.Internal.Rpc Proto.Jonline.Membership Proto.Google.Protobuf.Empty
deleteMembership =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteMembership"
        , encoder = Proto.Jonline.encodeMembership
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateMembership' sending a `Membership` to get back a `Membership`.

 Update aspects of a user's membership. *Authenticated.*
 Updating permissions requires `ADMIN` permissions within the group, or `ADMIN` permissions for the user.
 Updating moderation (approving/denying/banning) requires the same, or `MODERATE_USERS` permissions within the group.


-}
updateMembership : Grpc.Internal.Rpc Proto.Jonline.Membership Proto.Jonline.Membership
updateMembership =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateMembership"
        , encoder = Proto.Jonline.encodeMembership
        , decoder = Proto.Jonline.decodeMembership
        }


{-| A template for a gRPC call to the method 'CreateMembership' sending a `Membership` to get back a `Membership`.

 Requests to join a group (or joins it), or sends an invite to the user. *Authenticated.*
 Memberships and moderations are set to their defaults.


-}
createMembership : Grpc.Internal.Rpc Proto.Jonline.Membership Proto.Jonline.Membership
createMembership =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateMembership"
        , encoder = Proto.Jonline.encodeMembership
        , decoder = Proto.Jonline.decodeMembership
        }


{-| A template for a gRPC call to the method 'GetMembers' sending a `GetMembersRequest` to get back a `GetMembersResponse`.

 Get Members (User+Membership) of a Group. *Publicly accessible **or** Authenticated.*


-}
getMembers : Grpc.Internal.Rpc Proto.Jonline.GetMembersRequest Proto.Jonline.GetMembersResponse
getMembers =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetMembers"
        , encoder = Proto.Jonline.encodeGetMembersRequest
        , decoder = Proto.Jonline.decodeGetMembersResponse
        }


{-| A template for a gRPC call to the method 'DeleteGroup' sending a `Group` to get back a `Empty`.

 Delete a Group. *Authenticated.*
 Requires `ADMIN` permissions within the group, or `ADMIN` permissions for the user.


-}
deleteGroup : Grpc.Internal.Rpc Proto.Jonline.Group Proto.Google.Protobuf.Empty
deleteGroup =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteGroup"
        , encoder = Proto.Jonline.encodeGroup
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateGroup' sending a `Group` to get back a `Group`.

 Update a Groups's information, default membership permissions or moderation. *Authenticated.*
 Requires `ADMIN` permissions within the group, or `ADMIN` permissions for the user.


-}
updateGroup : Grpc.Internal.Rpc Proto.Jonline.Group Proto.Jonline.Group
updateGroup =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateGroup"
        , encoder = Proto.Jonline.encodeGroup
        , decoder = Proto.Jonline.decodeGroup
        }


{-| A template for a gRPC call to the method 'CreateGroup' sending a `Group` to get back a `Group`.

 Creates a group with the current user as its admin. *Authenticated.*
 Requires the `CREATE_GROUPS` permission.


-}
createGroup : Grpc.Internal.Rpc Proto.Jonline.Group Proto.Jonline.Group
createGroup =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateGroup"
        , encoder = Proto.Jonline.encodeGroup
        , decoder = Proto.Jonline.decodeGroup
        }


{-| A template for a gRPC call to the method 'GetGroups' sending a `GetGroupsRequest` to get back a `GetGroupsResponse`.

 Gets Groups. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Groups of `GLOBAL_PUBLIC` visibility.


-}
getGroups : Grpc.Internal.Rpc Proto.Jonline.GetGroupsRequest Proto.Jonline.GetGroupsResponse
getGroups =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetGroups"
        , encoder = Proto.Jonline.encodeGetGroupsRequest
        , decoder = Proto.Jonline.decodeGetGroupsResponse
        }


{-| A template for a gRPC call to the method 'DeleteFollow' sending a `Follow` to get back a `Empty`.

 Unfollow (or unrequest) a user. *Authenticated.*


-}
deleteFollow : Grpc.Internal.Rpc Proto.Jonline.Follow Proto.Google.Protobuf.Empty
deleteFollow =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteFollow"
        , encoder = Proto.Jonline.encodeFollow
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateFollow' sending a `Follow` to get back a `Follow`.

 Used to approve follow requests. *Authenticated.*


-}
updateFollow : Grpc.Internal.Rpc Proto.Jonline.Follow Proto.Jonline.Follow
updateFollow =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateFollow"
        , encoder = Proto.Jonline.encodeFollow
        , decoder = Proto.Jonline.decodeFollow
        }


{-| A template for a gRPC call to the method 'CreateFollow' sending a `Follow` to get back a `Follow`.

 Follow (or request to follow) a user. *Authenticated.*


-}
createFollow : Grpc.Internal.Rpc Proto.Jonline.Follow Proto.Jonline.Follow
createFollow =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateFollow"
        , encoder = Proto.Jonline.encodeFollow
        , decoder = Proto.Jonline.decodeFollow
        }


{-| A template for a gRPC call to the method 'DeleteUser' sending a `User` to get back a `Empty`.

 Deletes a user by ID. *Authenticated.*
 Deleting other users requires `ADMIN` permissions.


-}
deleteUser : Grpc.Internal.Rpc Proto.Jonline.User Proto.Google.Protobuf.Empty
deleteUser =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteUser"
        , encoder = Proto.Jonline.encodeUser
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'UpdateUser' sending a `User` to get back a `User`.

 Update a user by ID. *Authenticated.*
 Updating other users requires `ADMIN` permissions.


-}
updateUser : Grpc.Internal.Rpc Proto.Jonline.User Proto.Jonline.User
updateUser =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "UpdateUser"
        , encoder = Proto.Jonline.encodeUser
        , decoder = Proto.Jonline.decodeUser
        }


{-| A template for a gRPC call to the method 'GetUsers' sending a `GetUsersRequest` to get back a `GetUsersResponse`.

 Gets Users. *Publicly accessible **or** Authenticated.*
 Unauthenticated calls only return Users of `GLOBAL_PUBLIC` visibility.


-}
getUsers : Grpc.Internal.Rpc Proto.Jonline.GetUsersRequest Proto.Jonline.GetUsersResponse
getUsers =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetUsers"
        , encoder = Proto.Jonline.encodeGetUsersRequest
        , decoder = Proto.Jonline.decodeGetUsersResponse
        }


{-| A template for a gRPC call to the method 'DeleteMedia' sending a `Media` to get back a `Empty`.

 Deletes a media item by ID. *Authenticated.* Note that media may still be accessible for 12 hours after deletes are requested, as separate jobs clean it up from S3/MinIO.
 Deleting other users' media requires `ADMIN` permissions.


-}
deleteMedia : Grpc.Internal.Rpc Proto.Jonline.Media Proto.Google.Protobuf.Empty
deleteMedia =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "DeleteMedia"
        , encoder = Proto.Jonline.encodeMedia
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'GetMedia' sending a `GetMediaRequest` to get back a `GetMediaResponse`.

 Gets Media (Images, Videos, etc) uploaded/owned by the current user. *Authenticated.* To upload/download actual Media blob/binary data, use the [HTTP Media APIs](#media).


-}
getMedia : Grpc.Internal.Rpc Proto.Jonline.GetMediaRequest Proto.Jonline.GetMediaResponse
getMedia =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetMedia"
        , encoder = Proto.Jonline.encodeGetMediaRequest
        , decoder = Proto.Jonline.decodeGetMediaResponse
        }


{-| A template for a gRPC call to the method 'ResetPassword' sending a `ResetPasswordRequest` to get back a `Empty`.

 Resets the current user's - or, for admins, a given user's - password. *Authenticated.*


-}
resetPassword : Grpc.Internal.Rpc Proto.Jonline.ResetPasswordRequest Proto.Google.Protobuf.Empty
resetPassword =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "ResetPassword"
        , encoder = Proto.Jonline.encodeResetPasswordRequest
        , decoder = Proto.Google.Protobuf.decodeEmpty
        }


{-| A template for a gRPC call to the method 'GetCurrentUser' sending a `Empty` to get back a `User`.

 Gets the current user. *Authenticated.*


-}
getCurrentUser : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Jonline.User
getCurrentUser =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetCurrentUser"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Jonline.decodeUser
        }


{-| A template for a gRPC call to the method 'AccessToken' sending a `AccessTokenRequest` to get back a `AccessTokenResponse`.

 Gets a new `access_token` (and possibly a new `refresh_token`, which should replace the old one in client storage), given a `refresh_token`. *Publicly accessible.*


-}
accessToken : Grpc.Internal.Rpc Proto.Jonline.AccessTokenRequest Proto.Jonline.AccessTokenResponse
accessToken =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "AccessToken"
        , encoder = Proto.Jonline.encodeAccessTokenRequest
        , decoder = Proto.Jonline.decodeAccessTokenResponse
        }


{-| A template for a gRPC call to the method 'Login' sending a `LoginRequest` to get back a `RefreshTokenResponse`.

 Logs in a user and provides a `refresh_token` (along with an `access_token`). *Publicly accessible.*


-}
login : Grpc.Internal.Rpc Proto.Jonline.LoginRequest Proto.Jonline.RefreshTokenResponse
login =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "Login"
        , encoder = Proto.Jonline.encodeLoginRequest
        , decoder = Proto.Jonline.decodeRefreshTokenResponse
        }


{-| A template for a gRPC call to the method 'CreateAccount' sending a `CreateAccountRequest` to get back a `RefreshTokenResponse`.

 Creates a user account and provides a `refresh_token` (along with an `access_token`). *Publicly accessible.*


-}
createAccount : Grpc.Internal.Rpc Proto.Jonline.CreateAccountRequest Proto.Jonline.RefreshTokenResponse
createAccount =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "CreateAccount"
        , encoder = Proto.Jonline.encodeCreateAccountRequest
        , decoder = Proto.Jonline.decodeRefreshTokenResponse
        }


{-| A template for a gRPC call to the method 'GetServerConfiguration' sending a `Empty` to get back a `ServerConfiguration`.

 Gets the Jonline server's configuration. *Publicly accessible.*


-}
getServerConfiguration : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Jonline.ServerConfiguration
getServerConfiguration =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetServerConfiguration"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Jonline.decodeServerConfiguration
        }


{-| A template for a gRPC call to the method 'GetServiceVersion' sending a `Empty` to get back a `GetServiceVersionResponse`.

 Get the version (from Cargo) of the Jonline service. *Publicly accessible.*


-}
getServiceVersion : Grpc.Internal.Rpc Proto.Google.Protobuf.Empty Proto.Jonline.GetServiceVersionResponse
getServiceVersion =
    Grpc.Internal.Rpc
        { service = "Jonline"
        , package = "jonline"
        , rpcName = "GetServiceVersion"
        , encoder = Proto.Google.Protobuf.encodeEmpty
        , decoder = Proto.Jonline.decodeGetServiceVersionResponse
        }
