{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.MessageListingType exposing (MessageListingType(..), decodeMessageListingType, defaultMessageListingType, encodeMessageListingType, fieldNumbersMessageListingType)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `messages.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs MessageListingType, decodeMessageListingType, defaultMessageListingType, encodeMessageListingType

@docs fieldNumbersMessageListingType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `MessageListingType`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersMessageListingType : MessageListingType -> Int
fieldNumbersMessageListingType n_ =
    case n_ of
        PERSONALMESSAGES ->
            0

        PERSONALMESSAGESTEXTSEARCH ->
            1

        ALLSYSTEMMESSAGES ->
            10

        ALLSYSTEMMESSAGESTEXTSEARCH ->
            11

        MessageListingTypeUnrecognized_ m_ ->
            m_


{-| Default for MessageListingType. Should only be used for 'required' decoders as an initial value.

-}
defaultMessageListingType : MessageListingType
defaultMessageListingType =
    PERSONALMESSAGES


{-| Declares how to encode a `MessageListingType` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeMessageListingType : MessageListingType -> Protobuf.Encode.Encoder
encodeMessageListingType value =
    Protobuf.Encode.int32 <|
        case value of
            PERSONALMESSAGES ->
                0

            PERSONALMESSAGESTEXTSEARCH ->
                1

            ALLSYSTEMMESSAGES ->
                10

            ALLSYSTEMMESSAGESTEXTSEARCH ->
                11

            MessageListingTypeUnrecognized_ i ->
                i


{-| Declares how to decode a `MessageListingType` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeMessageListingType : Protobuf.Decode.Decoder MessageListingType
decodeMessageListingType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        PERSONALMESSAGES

                    1 ->
                        PERSONALMESSAGESTEXTSEARCH

                    10 ->
                        ALLSYSTEMMESSAGES

                    11 ->
                        ALLSYSTEMMESSAGESTEXTSEARCH

                    _ ->
                        MessageListingTypeUnrecognized_ i
            )


{-| `MessageListingType` enumeration

-}
type MessageListingType
    = PERSONALMESSAGES
    | PERSONALMESSAGESTEXTSEARCH
    | ALLSYSTEMMESSAGES
    | ALLSYSTEMMESSAGESTEXTSEARCH
    | MessageListingTypeUnrecognized_ Int
