{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.Moderation exposing (Moderation(..), decodeModeration, defaultModeration, encodeModeration, fieldNumbersModeration)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `visibility_moderation.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Moderation, decodeModeration, defaultModeration, encodeModeration, fieldNumbersModeration

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Moderation`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersModeration : Moderation -> Int
fieldNumbersModeration n_ =
    case n_ of
        MODERATIONUNKNOWN ->
            0

        UNMODERATED ->
            1

        PENDING ->
            2

        APPROVED ->
            3

        REJECTED ->
            4

        ModerationUnrecognized_ m_ ->
            m_


{-| Default for Moderation. Should only be used for 'required' decoders as an initial value.

-}
defaultModeration : Moderation
defaultModeration =
    MODERATIONUNKNOWN


{-| Declares how to encode a `Moderation` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeModeration : Moderation -> Protobuf.Encode.Encoder
encodeModeration value =
    Protobuf.Encode.int32 <|
        case value of
            MODERATIONUNKNOWN ->
                0

            UNMODERATED ->
                1

            PENDING ->
                2

            APPROVED ->
                3

            REJECTED ->
                4

            ModerationUnrecognized_ i ->
                i


{-| Declares how to decode a `Moderation` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeModeration : Protobuf.Decode.Decoder Moderation
decodeModeration =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        MODERATIONUNKNOWN

                    1 ->
                        UNMODERATED

                    2 ->
                        PENDING

                    3 ->
                        APPROVED

                    4 ->
                        REJECTED

                    _ ->
                        ModerationUnrecognized_ i
            )


{-| `Moderation` enumeration

-}
type Moderation
    = MODERATIONUNKNOWN
    | UNMODERATED
    | PENDING
    | APPROVED
    | REJECTED
    | ModerationUnrecognized_ Int
