{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.NavigationTab exposing (NavigationTab(..), decodeNavigationTab, defaultNavigationTab, encodeNavigationTab, fieldNumbersNavigationTab)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs NavigationTab, decodeNavigationTab, defaultNavigationTab, encodeNavigationTab, fieldNumbersNavigationTab

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `NavigationTab`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersNavigationTab : NavigationTab -> Int
fieldNumbersNavigationTab n_ =
    case n_ of
        HOMETAB ->
            0

        EVENTSTAB ->
            10

        POSTSTAB ->
            11

        PEOPLETAB ->
            12

        ABOUTTAB ->
            15

        NavigationTabUnrecognized_ m_ ->
            m_


{-| Default for NavigationTab. Should only be used for 'required' decoders as an initial value.

-}
defaultNavigationTab : NavigationTab
defaultNavigationTab =
    HOMETAB


{-| Declares how to encode a `NavigationTab` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeNavigationTab : NavigationTab -> Protobuf.Encode.Encoder
encodeNavigationTab value =
    Protobuf.Encode.int32 <|
        case value of
            HOMETAB ->
                0

            EVENTSTAB ->
                10

            POSTSTAB ->
                11

            PEOPLETAB ->
                12

            ABOUTTAB ->
                15

            NavigationTabUnrecognized_ i ->
                i


{-| Declares how to decode a `NavigationTab` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeNavigationTab : Protobuf.Decode.Decoder NavigationTab
decodeNavigationTab =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        HOMETAB

                    10 ->
                        EVENTSTAB

                    11 ->
                        POSTSTAB

                    12 ->
                        PEOPLETAB

                    15 ->
                        ABOUTTAB

                    _ ->
                        NavigationTabUnrecognized_ i
            )


{-| `NavigationTab` enumeration

-}
type NavigationTab
    = HOMETAB
    | EVENTSTAB
    | POSTSTAB
    | PEOPLETAB
    | ABOUTTAB
    | NavigationTabUnrecognized_ Int
