{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.Permission exposing (Permission(..), decodePermission, defaultPermission, encodePermission, fieldNumbersPermission)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `permissions.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Permission, decodePermission, defaultPermission, encodePermission, fieldNumbersPermission

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Permission`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersPermission : Permission -> Int
fieldNumbersPermission n_ =
    case n_ of
        PERMISSIONUNKNOWN ->
            0

        VIEWUSERS ->
            1

        PUBLISHUSERSLOCALLY ->
            2

        PUBLISHUSERSGLOBALLY ->
            3

        MODERATEUSERS ->
            4

        FOLLOWUSERS ->
            5

        GRANTBASICPERMISSIONS ->
            6

        VIEWGROUPS ->
            10

        CREATEGROUPS ->
            11

        PUBLISHGROUPSLOCALLY ->
            12

        PUBLISHGROUPSGLOBALLY ->
            13

        MODERATEGROUPS ->
            14

        JOINGROUPS ->
            15

        INVITEGROUPMEMBERS ->
            16

        VIEWPOSTS ->
            20

        CREATEPOSTS ->
            21

        PUBLISHPOSTSLOCALLY ->
            22

        PUBLISHPOSTSGLOBALLY ->
            23

        MODERATEPOSTS ->
            24

        REPLYTOPOSTS ->
            25

        VIEWEVENTS ->
            30

        CREATEEVENTS ->
            31

        PUBLISHEVENTSLOCALLY ->
            32

        PUBLISHEVENTSGLOBALLY ->
            33

        MODERATEEVENTS ->
            34

        RSVPTOEVENTS ->
            35

        VIEWMEDIA ->
            40

        CREATEMEDIA ->
            41

        PUBLISHMEDIALOCALLY ->
            42

        PUBLISHMEDIAGLOBALLY ->
            43

        MODERATEMEDIA ->
            44

        BUSINESS ->
            9998

        RUNBOTS ->
            9999

        ADMIN ->
            10000

        VIEWPRIVATECONTACTMETHODS ->
            10001

        PermissionUnrecognized_ m_ ->
            m_


{-| Default for Permission. Should only be used for 'required' decoders as an initial value.

-}
defaultPermission : Permission
defaultPermission =
    PERMISSIONUNKNOWN


{-| Declares how to encode a `Permission` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodePermission : Permission -> Protobuf.Encode.Encoder
encodePermission value =
    Protobuf.Encode.int32 <|
        case value of
            PERMISSIONUNKNOWN ->
                0

            VIEWUSERS ->
                1

            PUBLISHUSERSLOCALLY ->
                2

            PUBLISHUSERSGLOBALLY ->
                3

            MODERATEUSERS ->
                4

            FOLLOWUSERS ->
                5

            GRANTBASICPERMISSIONS ->
                6

            VIEWGROUPS ->
                10

            CREATEGROUPS ->
                11

            PUBLISHGROUPSLOCALLY ->
                12

            PUBLISHGROUPSGLOBALLY ->
                13

            MODERATEGROUPS ->
                14

            JOINGROUPS ->
                15

            INVITEGROUPMEMBERS ->
                16

            VIEWPOSTS ->
                20

            CREATEPOSTS ->
                21

            PUBLISHPOSTSLOCALLY ->
                22

            PUBLISHPOSTSGLOBALLY ->
                23

            MODERATEPOSTS ->
                24

            REPLYTOPOSTS ->
                25

            VIEWEVENTS ->
                30

            CREATEEVENTS ->
                31

            PUBLISHEVENTSLOCALLY ->
                32

            PUBLISHEVENTSGLOBALLY ->
                33

            MODERATEEVENTS ->
                34

            RSVPTOEVENTS ->
                35

            VIEWMEDIA ->
                40

            CREATEMEDIA ->
                41

            PUBLISHMEDIALOCALLY ->
                42

            PUBLISHMEDIAGLOBALLY ->
                43

            MODERATEMEDIA ->
                44

            BUSINESS ->
                9998

            RUNBOTS ->
                9999

            ADMIN ->
                10000

            VIEWPRIVATECONTACTMETHODS ->
                10001

            PermissionUnrecognized_ i ->
                i


{-| Declares how to decode a `Permission` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodePermission : Protobuf.Decode.Decoder Permission
decodePermission =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        PERMISSIONUNKNOWN

                    1 ->
                        VIEWUSERS

                    2 ->
                        PUBLISHUSERSLOCALLY

                    3 ->
                        PUBLISHUSERSGLOBALLY

                    4 ->
                        MODERATEUSERS

                    5 ->
                        FOLLOWUSERS

                    6 ->
                        GRANTBASICPERMISSIONS

                    10 ->
                        VIEWGROUPS

                    11 ->
                        CREATEGROUPS

                    12 ->
                        PUBLISHGROUPSLOCALLY

                    13 ->
                        PUBLISHGROUPSGLOBALLY

                    14 ->
                        MODERATEGROUPS

                    15 ->
                        JOINGROUPS

                    16 ->
                        INVITEGROUPMEMBERS

                    20 ->
                        VIEWPOSTS

                    21 ->
                        CREATEPOSTS

                    22 ->
                        PUBLISHPOSTSLOCALLY

                    23 ->
                        PUBLISHPOSTSGLOBALLY

                    24 ->
                        MODERATEPOSTS

                    25 ->
                        REPLYTOPOSTS

                    30 ->
                        VIEWEVENTS

                    31 ->
                        CREATEEVENTS

                    32 ->
                        PUBLISHEVENTSLOCALLY

                    33 ->
                        PUBLISHEVENTSGLOBALLY

                    34 ->
                        MODERATEEVENTS

                    35 ->
                        RSVPTOEVENTS

                    40 ->
                        VIEWMEDIA

                    41 ->
                        CREATEMEDIA

                    42 ->
                        PUBLISHMEDIALOCALLY

                    43 ->
                        PUBLISHMEDIAGLOBALLY

                    44 ->
                        MODERATEMEDIA

                    9998 ->
                        BUSINESS

                    9999 ->
                        RUNBOTS

                    10000 ->
                        ADMIN

                    10001 ->
                        VIEWPRIVATECONTACTMETHODS

                    _ ->
                        PermissionUnrecognized_ i
            )


{-| `Permission` enumeration

-}
type Permission
    = PERMISSIONUNKNOWN
    | VIEWUSERS
    | PUBLISHUSERSLOCALLY
    | PUBLISHUSERSGLOBALLY
    | MODERATEUSERS
    | FOLLOWUSERS
    | GRANTBASICPERMISSIONS
    | VIEWGROUPS
    | CREATEGROUPS
    | PUBLISHGROUPSLOCALLY
    | PUBLISHGROUPSGLOBALLY
    | MODERATEGROUPS
    | JOINGROUPS
    | INVITEGROUPMEMBERS
    | VIEWPOSTS
    | CREATEPOSTS
    | PUBLISHPOSTSLOCALLY
    | PUBLISHPOSTSGLOBALLY
    | MODERATEPOSTS
    | REPLYTOPOSTS
    | VIEWEVENTS
    | CREATEEVENTS
    | PUBLISHEVENTSLOCALLY
    | PUBLISHEVENTSGLOBALLY
    | MODERATEEVENTS
    | RSVPTOEVENTS
    | VIEWMEDIA
    | CREATEMEDIA
    | PUBLISHMEDIALOCALLY
    | PUBLISHMEDIAGLOBALLY
    | MODERATEMEDIA
    | BUSINESS
    | RUNBOTS
    | ADMIN
    | VIEWPRIVATECONTACTMETHODS
    | PermissionUnrecognized_ Int
