{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.PostContext exposing (PostContext(..), decodePostContext, defaultPostContext, encodePostContext, fieldNumbersPostContext)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `posts.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs PostContext, decodePostContext, defaultPostContext, encodePostContext, fieldNumbersPostContext

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `PostContext`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersPostContext : PostContext -> Int
fieldNumbersPostContext n_ =
    case n_ of
        POST ->
            0

        REPLY ->
            1

        EVENT ->
            2

        EVENTINSTANCE ->
            3

        FEDERATEDPOST ->
            10

        FEDERATEDEVENTINSTANCE ->
            13

        PostContextUnrecognized_ m_ ->
            m_


{-| Default for PostContext. Should only be used for 'required' decoders as an initial value.

-}
defaultPostContext : PostContext
defaultPostContext =
    POST


{-| Declares how to encode a `PostContext` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodePostContext : PostContext -> Protobuf.Encode.Encoder
encodePostContext value =
    Protobuf.Encode.int32 <|
        case value of
            POST ->
                0

            REPLY ->
                1

            EVENT ->
                2

            EVENTINSTANCE ->
                3

            FEDERATEDPOST ->
                10

            FEDERATEDEVENTINSTANCE ->
                13

            PostContextUnrecognized_ i ->
                i


{-| Declares how to decode a `PostContext` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodePostContext : Protobuf.Decode.Decoder PostContext
decodePostContext =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        POST

                    1 ->
                        REPLY

                    2 ->
                        EVENT

                    3 ->
                        EVENTINSTANCE

                    10 ->
                        FEDERATEDPOST

                    13 ->
                        FEDERATEDEVENTINSTANCE

                    _ ->
                        PostContextUnrecognized_ i
            )


{-| `PostContext` enumeration

-}
type PostContext
    = POST
    | REPLY
    | EVENT
    | EVENTINSTANCE
    | FEDERATEDPOST
    | FEDERATEDEVENTINSTANCE
    | PostContextUnrecognized_ Int
