{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.PostMediaLayout exposing (PostMediaLayout(..), decodePostMediaLayout, defaultPostMediaLayout, encodePostMediaLayout, fieldNumbersPostMediaLayout)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `posts.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs PostMediaLayout, decodePostMediaLayout, defaultPostMediaLayout, encodePostMediaLayout, fieldNumbersPostMediaLayout

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `PostMediaLayout`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersPostMediaLayout : PostMediaLayout -> Int
fieldNumbersPostMediaLayout n_ =
    case n_ of
        MEDIALAYOUTSTANDARD ->
            0

        MEDIALAYOUTDYNAMICVERTICALSCROLL ->
            1

        PostMediaLayoutUnrecognized_ m_ ->
            m_


{-| Default for PostMediaLayout. Should only be used for 'required' decoders as an initial value.

-}
defaultPostMediaLayout : PostMediaLayout
defaultPostMediaLayout =
    MEDIALAYOUTSTANDARD


{-| Declares how to encode a `PostMediaLayout` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodePostMediaLayout : PostMediaLayout -> Protobuf.Encode.Encoder
encodePostMediaLayout value =
    Protobuf.Encode.int32 <|
        case value of
            MEDIALAYOUTSTANDARD ->
                0

            MEDIALAYOUTDYNAMICVERTICALSCROLL ->
                1

            PostMediaLayoutUnrecognized_ i ->
                i


{-| Declares how to decode a `PostMediaLayout` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodePostMediaLayout : Protobuf.Decode.Decoder PostMediaLayout
decodePostMediaLayout =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        MEDIALAYOUTSTANDARD

                    1 ->
                        MEDIALAYOUTDYNAMICVERTICALSCROLL

                    _ ->
                        PostMediaLayoutUnrecognized_ i
            )


{-| `PostMediaLayout` enumeration

-}
type PostMediaLayout
    = MEDIALAYOUTSTANDARD
    | MEDIALAYOUTDYNAMICVERTICALSCROLL
    | PostMediaLayoutUnrecognized_ Int
