{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.PostListingType exposing (PostListingType(..), decodePostListingType, defaultPostListingType, encodePostListingType, fieldNumbersPostListingType)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `posts.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs PostListingType, decodePostListingType, defaultPostListingType, encodePostListingType, fieldNumbersPostListingType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `PostListingType`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersPostListingType : PostListingType -> Int
fieldNumbersPostListingType n_ =
    case n_ of
        ALLACCESSIBLEPOSTS ->
            0

        FOLLOWINGPOSTS ->
            1

        MYGROUPSPOSTS ->
            2

        DIRECTPOSTS ->
            3

        POSTSPENDINGMODERATION ->
            4

        TEXTSEARCH ->
            5

        GROUPPOSTS ->
            10

        GROUPPOSTSPENDINGMODERATION ->
            11

        PostListingTypeUnrecognized_ m_ ->
            m_


{-| Default for PostListingType. Should only be used for 'required' decoders as an initial value.

-}
defaultPostListingType : PostListingType
defaultPostListingType =
    ALLACCESSIBLEPOSTS


{-| Declares how to encode a `PostListingType` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodePostListingType : PostListingType -> Protobuf.Encode.Encoder
encodePostListingType value =
    Protobuf.Encode.int32 <|
        case value of
            ALLACCESSIBLEPOSTS ->
                0

            FOLLOWINGPOSTS ->
                1

            MYGROUPSPOSTS ->
                2

            DIRECTPOSTS ->
                3

            POSTSPENDINGMODERATION ->
                4

            TEXTSEARCH ->
                5

            GROUPPOSTS ->
                10

            GROUPPOSTSPENDINGMODERATION ->
                11

            PostListingTypeUnrecognized_ i ->
                i


{-| Declares how to decode a `PostListingType` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodePostListingType : Protobuf.Decode.Decoder PostListingType
decodePostListingType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        ALLACCESSIBLEPOSTS

                    1 ->
                        FOLLOWINGPOSTS

                    2 ->
                        MYGROUPSPOSTS

                    3 ->
                        DIRECTPOSTS

                    4 ->
                        POSTSPENDINGMODERATION

                    5 ->
                        TEXTSEARCH

                    10 ->
                        GROUPPOSTS

                    11 ->
                        GROUPPOSTSPENDINGMODERATION

                    _ ->
                        PostListingTypeUnrecognized_ i
            )


{-| `PostListingType` enumeration

-}
type PostListingType
    = ALLACCESSIBLEPOSTS
    | FOLLOWINGPOSTS
    | MYGROUPSPOSTS
    | DIRECTPOSTS
    | POSTSPENDINGMODERATION
    | TEXTSEARCH
    | GROUPPOSTS
    | GROUPPOSTSPENDINGMODERATION
    | PostListingTypeUnrecognized_ Int
