{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.PrivateUserStrategy exposing (PrivateUserStrategy(..), decodePrivateUserStrategy, defaultPrivateUserStrategy, encodePrivateUserStrategy, fieldNumbersPrivateUserStrategy)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs PrivateUserStrategy, decodePrivateUserStrategy, defaultPrivateUserStrategy, encodePrivateUserStrategy

@docs fieldNumbersPrivateUserStrategy

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `PrivateUserStrategy`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersPrivateUserStrategy : PrivateUserStrategy -> Int
fieldNumbersPrivateUserStrategy n_ =
    case n_ of
        ACCOUNTISFROZEN ->
            0

        LIMITEDCREEPINESS ->
            1

        LETMECREEPONPPL ->
            2

        PrivateUserStrategyUnrecognized_ m_ ->
            m_


{-| Default for PrivateUserStrategy. Should only be used for 'required' decoders as an initial value.

-}
defaultPrivateUserStrategy : PrivateUserStrategy
defaultPrivateUserStrategy =
    ACCOUNTISFROZEN


{-| Declares how to encode a `PrivateUserStrategy` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodePrivateUserStrategy : PrivateUserStrategy -> Protobuf.Encode.Encoder
encodePrivateUserStrategy value =
    Protobuf.Encode.int32 <|
        case value of
            ACCOUNTISFROZEN ->
                0

            LIMITEDCREEPINESS ->
                1

            LETMECREEPONPPL ->
                2

            PrivateUserStrategyUnrecognized_ i ->
                i


{-| Declares how to decode a `PrivateUserStrategy` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodePrivateUserStrategy : Protobuf.Decode.Decoder PrivateUserStrategy
decodePrivateUserStrategy =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        ACCOUNTISFROZEN

                    1 ->
                        LIMITEDCREEPINESS

                    2 ->
                        LETMECREEPONPPL

                    _ ->
                        PrivateUserStrategyUnrecognized_ i
            )


{-| `PrivateUserStrategy` enumeration

-}
type PrivateUserStrategy
    = ACCOUNTISFROZEN
    | LIMITEDCREEPINESS
    | LETMECREEPONPPL
    | PrivateUserStrategyUnrecognized_ Int
