{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.UserListingType exposing (UserListingType(..), decodeUserListingType, defaultUserListingType, encodeUserListingType, fieldNumbersUserListingType)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `users.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs UserListingType, decodeUserListingType, defaultUserListingType, encodeUserListingType, fieldNumbersUserListingType

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `UserListingType`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersUserListingType : UserListingType -> Int
fieldNumbersUserListingType n_ =
    case n_ of
        EVERYONE ->
            0

        FOLLOWING ->
            1

        FRIENDS ->
            2

        FOLLOWERS ->
            3

        FOLLOWREQUESTS ->
            4

        USERSTEXTSEARCH ->
            5

        FOLLOWERSTEXTSEARCH ->
            6

        FOLLOWINGTEXTSEARCH ->
            7

        FRIENDSTEXTSEARCH ->
            8

        FOLLOWREQUESTSTEXTSEARCH ->
            9

        ADMINS ->
            10

        UserListingTypeUnrecognized_ m_ ->
            m_


{-| Default for UserListingType. Should only be used for 'required' decoders as an initial value.

-}
defaultUserListingType : UserListingType
defaultUserListingType =
    EVERYONE


{-| Declares how to encode a `UserListingType` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeUserListingType : UserListingType -> Protobuf.Encode.Encoder
encodeUserListingType value =
    Protobuf.Encode.int32 <|
        case value of
            EVERYONE ->
                0

            FOLLOWING ->
                1

            FRIENDS ->
                2

            FOLLOWERS ->
                3

            FOLLOWREQUESTS ->
                4

            USERSTEXTSEARCH ->
                5

            FOLLOWERSTEXTSEARCH ->
                6

            FOLLOWINGTEXTSEARCH ->
                7

            FRIENDSTEXTSEARCH ->
                8

            FOLLOWREQUESTSTEXTSEARCH ->
                9

            ADMINS ->
                10

            UserListingTypeUnrecognized_ i ->
                i


{-| Declares how to decode a `UserListingType` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeUserListingType : Protobuf.Decode.Decoder UserListingType
decodeUserListingType =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        EVERYONE

                    1 ->
                        FOLLOWING

                    2 ->
                        FRIENDS

                    3 ->
                        FOLLOWERS

                    4 ->
                        FOLLOWREQUESTS

                    5 ->
                        USERSTEXTSEARCH

                    6 ->
                        FOLLOWERSTEXTSEARCH

                    7 ->
                        FOLLOWINGTEXTSEARCH

                    8 ->
                        FRIENDSTEXTSEARCH

                    9 ->
                        FOLLOWREQUESTSTEXTSEARCH

                    10 ->
                        ADMINS

                    _ ->
                        UserListingTypeUnrecognized_ i
            )


{-| `UserListingType` enumeration

-}
type UserListingType
    = EVERYONE
    | FOLLOWING
    | FRIENDS
    | FOLLOWERS
    | FOLLOWREQUESTS
    | USERSTEXTSEARCH
    | FOLLOWERSTEXTSEARCH
    | FOLLOWINGTEXTSEARCH
    | FRIENDSTEXTSEARCH
    | FOLLOWREQUESTSTEXTSEARCH
    | ADMINS
    | UserListingTypeUnrecognized_ Int
