{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.Visibility exposing (Visibility(..), decodeVisibility, defaultVisibility, encodeVisibility, fieldNumbersVisibility)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.26.1
- the following specification files: `visibility_moderation.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs Visibility, decodeVisibility, defaultVisibility, encodeVisibility, fieldNumbersVisibility

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `Visibility`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersVisibility : Visibility -> Int
fieldNumbersVisibility n_ =
    case n_ of
        VISIBILITYUNKNOWN ->
            0

        PRIVATE ->
            1

        LIMITED ->
            2

        SERVERPUBLIC ->
            3

        GLOBALPUBLIC ->
            4

        DIRECT ->
            5

        VisibilityUnrecognized_ m_ ->
            m_


{-| Default for Visibility. Should only be used for 'required' decoders as an initial value.

-}
defaultVisibility : Visibility
defaultVisibility =
    VISIBILITYUNKNOWN


{-| Declares how to encode a `Visibility` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeVisibility : Visibility -> Protobuf.Encode.Encoder
encodeVisibility value =
    Protobuf.Encode.int32 <|
        case value of
            VISIBILITYUNKNOWN ->
                0

            PRIVATE ->
                1

            LIMITED ->
                2

            SERVERPUBLIC ->
                3

            GLOBALPUBLIC ->
                4

            DIRECT ->
                5

            VisibilityUnrecognized_ i ->
                i


{-| Declares how to decode a `Visibility` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeVisibility : Protobuf.Decode.Decoder Visibility
decodeVisibility =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        VISIBILITYUNKNOWN

                    1 ->
                        PRIVATE

                    2 ->
                        LIMITED

                    3 ->
                        SERVERPUBLIC

                    4 ->
                        GLOBALPUBLIC

                    5 ->
                        DIRECT

                    _ ->
                        VisibilityUnrecognized_ i
            )


{-| `Visibility` enumeration

-}
type Visibility
    = VISIBILITYUNKNOWN
    | PRIVATE
    | LIMITED
    | SERVERPUBLIC
    | GLOBALPUBLIC
    | DIRECT
    | VisibilityUnrecognized_ Int
