{- !!! DO NOT EDIT THIS FILE MANUALLY !!! -}

module Proto.Jonline.WebUserInterface exposing (WebUserInterface(..), decodeWebUserInterface, defaultWebUserInterface, encodeWebUserInterface, fieldNumbersWebUserInterface)

{-| 
This file was automatically generated by
- [`protoc-gen-elm`](https://www.npmjs.com/package/protoc-gen-elm) 4.0.4
- `protoc` 5.29.3
- the following specification files: `server_configuration.proto`

To run it, add a dependency via `elm install` on [`elm-protocol-buffers`](https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/1.2.0) version latest or higher.

@docs WebUserInterface, decodeWebUserInterface, defaultWebUserInterface, encodeWebUserInterface, fieldNumbersWebUserInterface

-}

import Protobuf.Decode
import Protobuf.Encode


{-| The field numbers for the fields of `WebUserInterface`. This is mostly useful for internals, like documentation generation.

-}
fieldNumbersWebUserInterface : WebUserInterface -> Int
fieldNumbersWebUserInterface n_ =
    case n_ of
        FLUTTERWEB ->
            0

        HANDLEBARSTEMPLATES ->
            1

        REACTTAMAGUI ->
            2

        ELMSPA ->
            3

        WebUserInterfaceUnrecognized_ m_ ->
            m_


{-| Default for WebUserInterface. Should only be used for 'required' decoders as an initial value.

-}
defaultWebUserInterface : WebUserInterface
defaultWebUserInterface =
    FLUTTERWEB


{-| Declares how to encode a `WebUserInterface` to Bytes. To actually perform the conversion to Bytes, you need to use Protobuf.Encode.encode from eriktim/elm-protocol-buffers.

-}
encodeWebUserInterface : WebUserInterface -> Protobuf.Encode.Encoder
encodeWebUserInterface value =
    Protobuf.Encode.int32 <|
        case value of
            FLUTTERWEB ->
                0

            HANDLEBARSTEMPLATES ->
                1

            REACTTAMAGUI ->
                2

            ELMSPA ->
                3

            WebUserInterfaceUnrecognized_ i ->
                i


{-| Declares how to decode a `WebUserInterface` from Bytes. To actually perform the conversion from Bytes, you need to use Protobuf.Decode.decode from eriktim/elm-protocol-buffers.

-}
decodeWebUserInterface : Protobuf.Decode.Decoder WebUserInterface
decodeWebUserInterface =
    Protobuf.Decode.int32
        |> Protobuf.Decode.map
            (\i ->
                case i of
                    0 ->
                        FLUTTERWEB

                    1 ->
                        HANDLEBARSTEMPLATES

                    2 ->
                        REACTTAMAGUI

                    3 ->
                        ELMSPA

                    _ ->
                        WebUserInterfaceUnrecognized_ i
            )


{-| `WebUserInterface` enumeration

-}
type WebUserInterface
    = FLUTTERWEB
    | HANDLEBARSTEMPLATES
    | REACTTAMAGUI
    | ELMSPA
    | WebUserInterfaceUnrecognized_ Int
