-- Your SQL goes here
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  username VARCHAR NOT NULL UNIQUE,
  password_salted_hash TEXT NOT NULL,
  email VARCHAR NULL DEFAULT NULL,
  phone VARCHAR NULL DEFAULT NULL
);

CREATE TABLE user_auth_tokens (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL DEFAULT NOW() + INTERVAL '1 day'
);

CREATE TABLE user_refresh_tokens (
  id SERIAL PRIMARY KEY,
  auth_token_id INTEGER NOT NULL REFERENCES user_auth_tokens ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMP NOT NULL DEFAULT NOW() + INTERVAL '1 day'
);

ALTER TABLE posts ADD user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE;
ALTER TABLE posts ADD parent_post_id INTEGER NULL DEFAULT NULL REFERENCES users ON DELETE SET NULL;