# Note that the deploy step expects that backend/Cargo.toml and deploys/k8s/server.yaml
# have the same version number.
name: Server CI/CD

on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        description: 'DockerHub username for CD'
        required: true
      DOCKERHUB_TOKEN:
        description: 'DockerHub access token for CD'
        required: true

jobs:
  build_flutter_ui:
    name: Build Flutter Web UI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Store Versioning Data for release ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: echo ${{ steps.vars.outputs.sha_short }} > deploys/docker/continuous_delivery_hash

    - uses: subosito/flutter-action@v2

    - working-directory: frontends/flutter
      run: flutter pub get
    # - working-directory: frontends/flutter
    #   run: flutter test
    - working-directory: frontends/flutter
      run: flutter build web --web-renderer canvaskit --release --base-href /flutter/

    - uses: actions/cache/save@v3
      id: flutter-app-cache
      with:
        path: frontends/flutter/build/web
        key: flutter-${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}


  build_tamagui_ui:
    name: Build Tamagui Web UI
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Store Versioning Data for release ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: echo ${{ steps.vars.outputs.sha_short }} > deploys/docker/continuous_delivery_hash
    
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - run: npm install --global yarn

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: 'echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT'

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-jonline-tamagui-build-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-jonline-tamagui-build-${{ hashFiles('**/yarn.lock') }}

    - working-directory: frontends/tamagui
      run: yarn install
    - working-directory: frontends/tamagui
      run: yarn vercel:install
    - working-directory: frontends/tamagui
      run: yarn tsc
    - working-directory: frontends/tamagui
      run: yarn web:prod:build

    - uses: actions/cache/save@v3
      id: web-app-cache
      with:
        path: frontends/tamagui/apps/next/out
        key: web-${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}

  build_rust_server_binaries:
    name: Build Rust Server
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Store Versioning Data for release ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: echo ${{ steps.vars.outputs.sha_short }} > deploys/docker/continuous_delivery_hash

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: arduino/setup-protoc@v2

    - uses: Swatinem/rust-cache@v2
      with:
        workspaces: ./backend -> target
        # default key
        key: jonline-${{ runner.OS }}-github-build
        shared-key: jonline-${{ runner.OS }}-github-build

    - working-directory: backend
      run: cargo build --release


    - uses: actions/cache/save@v3
      id: rust-app-cache
      with:
        path: backend/target/release
        key: rust-${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}

  test_rust_server:
    name: Test Rust Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: arduino/setup-protoc@v2
      # - run: sudo apt install libprotobuf-dev protobuf-compiler

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ./backend -> target
          # default key
          key: jonline-${{ runner.OS }}-github-test
          shared-key: jonline-${{ runner.OS }}-github-test
      - working-directory: backend
        run: cargo test --all-features
      - working-directory: backend
        run: cargo build --all-features

  test_tamagui_ui:
    name: Test Tamagui Web UI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install --global yarn

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: 'echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT'

    - uses: actions/cache@v3
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-jonline-tamagui-test-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-jonline-tamagui-test-${{ hashFiles('**/yarn.lock') }}

    - working-directory: frontends/tamagui
      run: yarn install
    - working-directory: frontends/tamagui
      run: yarn vercel:install
    - working-directory: frontends/tamagui
      run: yarn build
    - working-directory: frontends/tamagui
      run: yarn tsc

  test_flutter_ui:
    name: Test Flutter Web UI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - working-directory: frontends/flutter
      run: flutter pub get
    - working-directory: frontends/flutter
      run: flutter test
    - working-directory: frontends/flutter
      run: flutter build web

  build_and_deliver_server:
    name: Build Server Image
    runs-on: ubuntu-latest
    needs:
      - build_flutter_ui
      - build_tamagui_ui
      - build_rust_server_binaries

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Store Versioning Data for release ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: echo ${{ steps.vars.outputs.sha_short }} > deploys/docker/continuous_delivery_hash


    - uses: actions/cache/restore@v3
      id: fllutter-app-cache
      with:
        path: frontends/flutter/build/web
        key: flutter-${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
    - uses: actions/cache/restore@v3
      id: web-app-cache
      with:
        path: frontends/tamagui/apps/next/out
        key: web-${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
    - uses: actions/cache/restore@v3
      id: rust-app-cache
      with:
        path: backend/target/release
        key: rust-${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}


    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Rename Rust binaries for Dockerfiles
      run: >-
           mv backend/target/release/jonline backend/target/release/jonline__server_release &&
           mv backend/target/release/disable_cdn_grpc backend/target/release/disable_cdn_grpc__server_release &&
           mv backend/target/release/delete_expired_tokens backend/target/release/delete_expired_tokens__server_release &&
           mv backend/target/release/delete_unowned_media backend/target/release/delete_unowned_media__server_release &&
           mv backend/target/release/generate_preview_images backend/target/release/generate_preview_images__server_release &&
           mv backend/target/release/delete_preview_images backend/target/release/delete_preview_images__server_release &&
           mv backend/target/release/set_permission backend/target/release/set_permission__server_release &&
           mv backend/target/release/to_db_id backend/target/release/to_db_id__server_release &&
           mv backend/target/release/to_proto_id backend/target/release/to_proto_id__server_release

    - name: Build and push jonline image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jonline:${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
        context: .
        file: ./deploys/docker/server/Dockerfile
        platforms: linux/amd64,linux/arm64

  build_and_deliver_preview_generator:
    name: Build Preview Generator Image
    runs-on: ubuntu-latest
    needs:
      - build_rust_server_binaries

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Store Versioning Data for release ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: echo ${{ steps.vars.outputs.sha_short }} > deploys/docker/continuous_delivery_hash

    - uses: actions/cache/restore@v3
      id: rust-app-cache
      with:
        path: backend/target/release
        key: rust-${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}


    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Rename Rust binaries for Dockerfiles
      run: >-
            mv backend/target/release/jonline backend/target/release/jonline__server_release &&
            mv backend/target/release/disable_cdn_grpc backend/target/release/disable_cdn_grpc__server_release &&
            mv backend/target/release/delete_expired_tokens backend/target/release/delete_expired_tokens__server_release &&
            mv backend/target/release/delete_unowned_media backend/target/release/delete_unowned_media__server_release &&
            mv backend/target/release/generate_preview_images backend/target/release/generate_preview_images__server_release &&
            mv backend/target/release/delete_preview_images backend/target/release/delete_preview_images__server_release &&
            mv backend/target/release/set_permission backend/target/release/set_permission__server_release

    - name: Build and push jonline_preview_generator image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/jonline_preview_generator:${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
        context: .
        file: ./deploys/docker/preview_generator/Dockerfile
        platforms: linux/amd64,linux/arm64

  # Note that the deploy expects that backend/Cargo.toml and deploys/k8s/server.yaml
  # have the same version number.
  deploy_to_jonlineio:
    name: Deploy to Jonline.io
    if: github.ref == 'refs/heads/main'
    needs: 
      - test_rust_server
      - test_flutter_ui
      - test_tamagui_ui
      - build_and_deliver_server
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Update deploys/k8s/server.yaml to use ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: sed -i 's|${{ steps.vars.outputs.be_version }}|${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}|' deploys/k8s/server.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 jonline-be

    - name: Deploy to Jonline.io via DigitalOcean Kubernetes
      run: kubectl apply -f deploys/k8s/server.yaml -n jonline

    - name: Verify Server deployment
      run: kubectl rollout status deployment/jonline -n jonline


  # Note that the deploy expects that backend/Cargo.toml and deploys/k8s/server.yaml
  # have the same version number.
  deploy_to_bullcitysocial:
    name: Deploy to Bull City Social
    needs: deploy_to_jonlineio
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Update deploys/k8s/server.yaml to use ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: sed -i 's|${{ steps.vars.outputs.be_version }}|${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}|' deploys/k8s/server.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 jonline-be

    - name: Deploy to Bull City Social via DigitalOcean Kubernetes
      run: kubectl apply -f deploys/k8s/server.yaml -n bullcitysocial

    - name: Verify Server deployment
      run: kubectl rollout status deployment/jonline -n bullcitysocial

  # Note that the deploy expects that backend/Cargo.toml and deploys/k8s/server.yaml
  # have the same version number.
  deploy_to_oakcitysocial:
    name: Deploy to Oak City Social
    needs: deploy_to_jonlineio
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Update deploys/k8s/server.yaml to use ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: sed -i 's|${{ steps.vars.outputs.be_version }}|${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}|' deploys/k8s/server.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 jonline-be

    - name: Deploy to Oak City Social via DigitalOcean Kubernetes
      run: kubectl apply -f deploys/k8s/server.yaml -n oakcitysocial

    - name: Verify Server deployment
      run: kubectl rollout status deployment/jonline -n oakcitysocial


  # Note that the deploy expects that backend/Cargo.toml and deploys/k8s/server.yaml
  # have the same version number.
  deploy_preview_generator:
    name: Deploy Preview Generator
    if: github.ref == 'refs/heads/main'

    needs: 
      - test_rust_server
      - test_flutter_ui
      - test_tamagui_ui
      - build_and_deliver_server
      - build_and_deliver_preview_generator
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Extract Versioning Data
      id: vars
      run: |-
        echo "be_version=$(cat backend/Cargo.toml | grep 'version =' | sed -n 1p | awk '{print $3;}' | sed 's/"//g')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Update deploys/k8s/preview_generator.yaml to use ${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}
      run: sed -i 's|${{ steps.vars.outputs.be_version }}|${{ steps.vars.outputs.be_version }}-${{ steps.vars.outputs.sha_short }}|' deploys/k8s/preview_generator.yaml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 jonline-be

    - name: Deploy to Jonline.io via DigitalOcean Kubernetes
      run: kubectl apply -f deploys/k8s/preview_generator.yaml -n jonline

    - name: Deploy to Bull City Social via DigitalOcean Kubernetes
      run: kubectl apply -f deploys/k8s/preview_generator.yaml -n bullcitysocial

    - name: Deploy to Oak City Social via DigitalOcean Kubernetes
      run: kubectl apply -f deploys/k8s/preview_generator.yaml -n oakcitysocial
