name: Flutter macOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_macos:
    name: Build
    # continue-on-error: true
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - working-directory: frontends/flutter
        run: flutter config --enable-macos-desktop
      - working-directory: frontends/flutter
        run: flutter build macos
