name: Flutter (Android)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_android:
    name: Build
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
      - working-directory: frontends/flutter
        run: flutter pub get
      - working-directory: frontends/flutter
        run: flutter build apk
      - working-directory: frontends/flutter
        run: flutter build appbundle
