name: Jonline CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend_build:
    name: Backend Build+Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: arduino/setup-protoc@v2
      - working-directory: backend
        run: cargo test --all-features
      - working-directory: backend
        run: cargo build --all-features

  tamagui_web_build:
    name: Tamagui Web Build+TSC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install --global yarn
    - working-directory: frontends/tamagui
      run: yarn install
    - working-directory: frontends/tamagui
      run: yarn vercel:install
    - working-directory: frontends/tamagui
      run: yarn build
    - working-directory: frontends/tamagui
      run: yarn tsc

  flutter_web_build:
    name: Flutter Web Build+Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - working-directory: frontends/flutter
      run: flutter pub get
    - working-directory: frontends/flutter
      run: flutter test
    - working-directory: frontends/flutter
      run: flutter build web

  build_and_deploy_image:
    name: Build and Deploy Image (Incomplete)
    needs: [backend_build, tamagui_web_build, flutter_web_build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: arduino/setup-protoc@v2
    - uses: subosito/flutter-action@v2
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install --global yarn

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    - working-directory: backend
      run: cargo build --release

    - working-directory: frontends/tamagui
      run: yarn install
    - working-directory: frontends/tamagui
      run: yarn vercel:install
    - working-directory: frontends/tamagui
      run: yarn web:prod_export

    - working-directory: frontends/flutter
      run: flutter pub get
    - working-directory: frontends/flutter
      run: flutter test
    - working-directory: frontends/flutter
      run: flutter build web --web-renderer canvaskit --release --base-href /flutter/

    - run: echo 'TODO Build and push image to DockerHub tagged with this git commit hash'

    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/jonline-ci:latest
    #     context: .
    #     file: ./Dockerfile
    #     platforms: linux/amd64,linux/arm64