name: Tamagui Frontend (Web)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build+Type Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - name: Install NPM Dependencies
      uses: borales/actions-yarn@v4
      with:
        working-directory: frontends/tamagui
        cmd: install # will run `yarn install` command
    - name: Check TypeScript Types
      uses: borales/actions-yarn@v4
      with:
        working-directory: frontends/tamagui
        cmd: tsc
    - name: Compile Web App
      uses: borales/actions-yarn@v4
      with:
        working-directory: frontends/tamagui
        cmd: web:prod:export