name: Tamagui Web

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build+TSC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install --global yarn
    - working-directory: frontends/tamagui
      run: yarn install
    - working-directory: frontends/tamagui
      run: yarn vercel:install
    - working-directory: frontends/tamagui
      run: yarn build
    - working-directory: frontends/tamagui
      run: yarn tsc
  export:
    name: Export (May Fail Silently)
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - run: npm install --global yarn
    - working-directory: frontends/tamagui
      run: yarn install
    - working-directory: frontends/tamagui
      run: yarn vercel:install
    - working-directory: frontends/tamagui
      run: yarn web:prod:export
  # export:
  #   name: Export (May Fail Silently)
  #   continue-on-error: true
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set Node.js 16.x
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 16.x
  #   - name: Install NPM Dependencies
  #     uses: borales/actions-yarn@v4
  #     with:
  #       dir: frontends/tamagui
  #       cmd: install # will run `yarn install` command
  #   - name: Compile Web App
  #     uses: borales/actions-yarn@v4
  #     with:
  #       dir: frontends/tamagui
  #       cmd: web:prod:export
